import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactPlugin from 'eslint-plugin-react';

export default [
	js.configs.recommended,
	{
		files: ['**/*.{ts,tsx}'],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				ecmaFeatures: { jsx: true },
				ecmaVersion: 'latest',
				sourceType: 'module',
			},
			globals: {
				window: 'readonly',
				document: 'readonly',
				navigator: 'readonly',
				console: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				requestAnimationFrame: 'readonly',
				cancelAnimationFrame: 'readonly',
				fetch: 'readonly',
				URL: 'readonly',
				HTMLElement: 'readonly',
				HTMLDivElement: 'readonly',
				HTMLCanvasElement: 'readonly',
				MouseEvent: 'readonly',
				KeyboardEvent: 'readonly',
				Event: 'readonly',
				EventTarget: 'readonly',
				CustomEvent: 'readonly',
				Map: 'readonly',
				Set: 'readonly',
				Promise: 'readonly',
				crypto: 'readonly',
				localStorage: 'readonly',
				sessionStorage: 'readonly',
				performance: 'readonly',
				Audio: 'readonly',
				Image: 'readonly',
				WebSocket: 'readonly',
				FormData: 'readonly',
				FileReader: 'readonly',
				Blob: 'readonly',
				atob: 'readonly',
				btoa: 'readonly',
				NodeJS: 'readonly',
				process: 'readonly',
				__dirname: 'readonly',
				module: 'readonly',
				require: 'readonly',
				exports: 'readonly',
				global: 'readonly',
				React: 'readonly',
				JSX: 'readonly',
			},
		},
		plugins: {
			'@typescript-eslint': tsPlugin,
			react: reactPlugin,
		},
		rules: {
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': 'warn',
			'no-console': 'warn',
			'react/prop-types': 'off',
			'react/react-in-jsx-scope': 'off',
			'@typescript-eslint/no-explicit-any': 'warn',
			'complexity': ['warn', 15],
			'camelcase': ['error', { properties: 'never', allow: ['^card_', '^effect_'] }],
			'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: ['state'] }],
		},
		settings: {
			react: { version: 'detect' },
		},
	},
	{
		ignores: ['node_modules/**', 'dist/**', '*.js', '*.cjs', '*.mjs'],
	},
];
