import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const c = (n: number) => 3000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => c(base + (j % 15)));

export const celticChapter: CampaignChapter = {
	id: 'celtic',
	name: 'Tir na nOg: The Otherworld',
	faction: 'celtic',
	description: 'Enter the mystical Otherworld of Celtic legend where fae and gods blur the line between dream and reality.',
	chapterReward: [{ type: 'pack', amount: 3 }, { type: 'rune', amount: 200 }],
	missions: [
		{
			id: 'celtic-1', chapterId: 'celtic', missionNumber: 1,
			name: 'Whispers of the Druids',
			description: 'Ancient druids guard the entrance to the Otherworld with living wood.',
			narrativeBefore: 'The forest is alive. Not metaphorically — the trees literally move, their roots sliding through soil like serpents. Druid elders stand at the tree line, their eyes glowing green. "The Otherworld is not for the uninvited," the eldest says, raising a staff that sprouts thorns. "Prove you belong."',
			narrativeAfter: 'The trees part, forming an archway of living wood. The druids bow their heads. "The forest accepts you. Walk the path that mortals fear."',
			narrativeVictory: 'The ancient wood bends to your will. The druids mark you as Otherworld-worthy.',
			narrativeDefeat: 'Roots coil around your ankles. The forest rejects you.',
			aiHeroId: 'hero-fjorgyn', aiHeroClass: 'druid',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 20 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-kvasir', rook: 'hero-baldur', bishop: 'hero-idunn', knight: 'hero-fjora' },
		},
		{
			id: 'celtic-2', chapterId: 'celtic', missionNumber: 2,
			name: 'The Morrigan\'s Crows',
			description: 'The phantom queen sends her dark flock as an omen of battle.',
			narrativeBefore: 'The sky turns black with crows — thousands of them, spiraling in patterns that spell doom. At their center, the Morrigan descends, shifting between maiden, mother, and crone in the space of a heartbeat. "I am the chooser of the slain," she whispers. "And I choose you."',
			narrativeAfter: 'The Morrigan\'s crows scatter. She watches you from the shadows with three pairs of eyes. "Interesting. You were not supposed to survive that."',
			narrativeVictory: 'The phantom queen\'s omens of death prove false. You defy fate itself.',
			narrativeDefeat: 'The crows descend. The Morrigan always collects what she is owed.',
			aiHeroId: 'hero-persephone', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.morrigan,
			bossRules: [], prerequisiteIds: ['celtic-1'],
			rewards: [{ type: 'rune', amount: 25 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-hel', rook: 'hero-vidar', bishop: 'hero-sigyn', knight: 'hero-nyx' },
		},
		{
			id: 'celtic-3', chapterId: 'celtic', missionNumber: 3,
			name: 'Cu Chulainn\'s Rage',
			description: 'The Hound of Ulster enters his legendary warp spasm.',
			narrativeBefore: 'He stands alone on the ford, one man against the world. Cu Chulainn, the Hound of Ulster, whose warp spasm twists his body into something barely human. His muscles ripple, his eye sinks into his skull, and blood-heat radiates from his skin. "I held the ford alone against an army," he growls. "You are just one."',
			narrativeAfter: 'Cu Chulainn\'s form untwists. He drives his spear into the ground and nods once. "Well fought. There is Ulster in your blood."',
			narrativeVictory: 'The greatest warrior of Celtic myth acknowledges your prowess.',
			narrativeDefeat: 'Cu Chulainn\'s gae bolga finds its mark. The Hound is unmatched.',
			aiHeroId: 'hero-vili', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.cuChulainn,
			bossRules: [{ type: 'extra_health', value: 5, description: 'Cu Chulainn\'s warp spasm grants extra vitality' }],
			prerequisiteIds: ['celtic-2'],
			rewards: [{ type: 'rune', amount: 30 }],
			campaignArmy: { king: 'king-surtr', queen: 'hero-sinmara', rook: 'hero-thor', bishop: 'hero-gerd', knight: 'hero-skadi' },
		},
		{
			id: 'celtic-4', chapterId: 'celtic', missionNumber: 4,
			name: 'The Salmon of Knowledge',
			description: 'Taste the Salmon of Wisdom and face the knowledge it brings.',
			narrativeBefore: 'The Well of Wisdom bubbles beneath the hazel trees. The Salmon of Knowledge circles in the sacred pool, scales shimmering with every secret ever whispered. Fionn mac Cumhaill gained all wisdom from a single taste of this fish. But wisdom is not free — the salmon has guardians, and knowledge has a price.',
			narrativeAfter: 'The Salmon leaps from the pool and touches your lips with its tail. A flood of knowledge rushes in — every battle tactic, every weakness, every hidden truth. The Otherworld has fewer secrets from you now.',
			narrativeVictory: 'Wisdom fills you. The Salmon of Knowledge deems you worthy of its gift.',
			narrativeDefeat: 'The Salmon slips away. Some knowledge must be earned with greater effort.',
			aiHeroId: 'hero-kvasir', aiHeroClass: 'mage',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.medium,
			bossRules: [{ type: 'bonus_draw', value: 1, description: 'The Salmon grants extra wisdom (bonus draw)' }],
			prerequisiteIds: ['celtic-3'],
			rewards: [{ type: 'rune', amount: 35 }, { type: 'eitr', amount: 50 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-odin', rook: 'hero-heimdall', bishop: 'hero-idunn', knight: 'hero-loki' },
		},
		{
			id: 'celtic-5', chapterId: 'celtic', missionNumber: 5,
			name: 'Balor of the Evil Eye',
			description: 'One glance from the Fomorian king\'s eye can destroy an army.',
			narrativeBefore: 'The ground trembles as Balor of the Evil Eye approaches, his cyclopean lid requiring four men to lift. When it opens, everything in its gaze withers and dies. Forests turn to ash. Mountains crack. He is the Fomorian king, and his eye has destroyed more than you can imagine. "Do not look," they whisper. But you must.',
			narrativeAfter: 'Balor\'s eye dims. The Fomorian king stumbles back, clutching his face. "The prophecy..." he mutters. "The light returns." His destructive gaze, for once, has met its match.',
			narrativeVictory: 'You withstand the gaze that destroyed armies. Balor\'s prophecy is fulfilled.',
			narrativeDefeat: 'The eye opens. Everything you are turns to nothing.',
			aiHeroId: 'hero-mani', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.balor,
			bossRules: [
				{ type: 'extra_health', value: 5, description: 'Balor has 105 health' },
				{ type: 'passive_damage', value: 1, description: 'Balor\'s Evil Eye deals 1 damage each turn' },
			],
			prerequisiteIds: ['celtic-4'],
			rewards: [{ type: 'rune', amount: 40 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-hades', rook: 'hero-logi', bishop: 'hero-ran', knight: 'hero-myrka' },
		},
		{
			id: 'celtic-6', chapterId: 'celtic', missionNumber: 6,
			name: 'The Dagda\'s Cauldron',
			description: 'The father-god of the Tuatha De Danann wields infinite power.',
			narrativeBefore: 'The Dagda is enormous — both in body and in spirit. He carries a club so large one end kills, the other resurrects. Before him sits his cauldron, the Undry, from which no one ever leaves unsatisfied. "Sit. Eat," he booms cheerfully. "And then we fight."',
			narrativeAfter: 'The Dagda laughs, a sound like boulders rolling. "Haven\'t been bested since Lugh himself challenged me!" He ladles out a bowl from the cauldron. "Eat. You\'ve earned it."',
			narrativeVictory: 'The father of gods falls laughing. His cauldron bubbles in approval.',
			narrativeDefeat: 'The Dagda\'s club swings once. That is enough.',
			aiHeroId: 'hero-hera', aiHeroClass: 'priest',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.dagda,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'The Dagda has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'The cauldron grants +1 mana' },
			],
			prerequisiteIds: ['celtic-5'],
			rewards: [{ type: 'rune', amount: 50 }, { type: 'card', cardId: 3200 }],
			campaignArmy: { king: 'king-buri', queen: 'hero-odin', rook: 'hero-thor', bishop: 'hero-freya', knight: 'hero-ullr' },
		},
		{
			id: 'celtic-7', chapterId: 'celtic', missionNumber: 7,
			name: 'Tir na nOg',
			description: 'The Land of Eternal Youth tempts you to stay forever.',
			narrativeBefore: 'Golden light spills across fields of impossible flowers. Tir na nOg, the Land of Eternal Youth — where no one ages, no one dies, and no one ever wants to leave. Niamh of the Golden Hair extends her hand. "Stay with me," she says. "Time has no power here." But you see the trap. Oisin stayed for what he thought was three years. Three hundred had passed.',
			narrativeAfter: 'You resist the pull of eternal paradise. The golden light fades, replaced by the honest grey of the Otherworld. Niamh weeps, but she understands. Some journeys must continue.',
			narrativeVictory: 'You resist eternity itself. The hardest battle is the one where victory means walking away.',
			narrativeDefeat: 'The fields are so beautiful. Just a moment longer... Three hundred years pass.',
			aiHeroId: 'hero-bragi', aiHeroClass: 'mage',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.hard,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Tir na nOg\'s guardians have 110 health' },
				{ type: 'bonus_draw', value: 1, description: 'Time flows strangely here (bonus draw)' },
			],
			prerequisiteIds: ['celtic-6'],
			rewards: [{ type: 'rune', amount: 55 }],
			campaignArmy: { king: 'king-audumbla', queen: 'hero-sol', rook: 'hero-baldur', bishop: 'hero-freya', knight: 'hero-fjora' },
		},
		{
			id: 'celtic-8', chapterId: 'celtic', missionNumber: 8,
			name: 'The Wild Hunt',
			description: 'Cernunnos leads the Wild Hunt across the midnight sky.',
			narrativeBefore: 'Horns blast across the Otherworld as Cernunnos, the Horned God, rides at the head of the Wild Hunt. Ghost riders pour through the sky on spectral horses, their hounds baying with voices like thunder. Once the Hunt chooses its quarry, it never stops. Never rests. Never fails. And tonight, you are the quarry.',
			narrativeAfter: 'Cernunnos reins in his spectral stag. The Hunt wheels around you but does not close. "You have outrun the Wild Hunt," the Horned God rumbles. "No mortal has done so in a thousand years."',
			narrativeVictory: 'The Hunt passes you by. Even Cernunnos acknowledges the untouchable.',
			narrativeDefeat: 'The Wild Hunt always catches its quarry. Always.',
			aiHeroId: 'hero-aegir', aiHeroClass: 'hunter',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.cernunnos,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Cernunnos has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'The Wild Hunt grants +1 mana' },
			],
			prerequisiteIds: ['celtic-7'],
			rewards: [{ type: 'rune', amount: 60 }, { type: 'eitr', amount: 100 }],
			campaignArmy: { king: 'king-ymir', queen: 'hero-sinmara', rook: 'hero-magni', bishop: 'hero-gerd', knight: 'hero-skadi' },
		},
		{
			id: 'celtic-9', chapterId: 'celtic', missionNumber: 9,
			name: 'Brigid\'s Forge',
			description: 'The triple goddess of fire, poetry, and healing tests your spirit in her forge.',
			narrativeBefore: 'The heat of Brigid\'s forge hits you before you see it — a fire that has burned since the dawn of the Celtic world. Brigid stands in triple aspect: the Smith who shapes weapons, the Healer who mends wounds, and the Poet who speaks truth. "To be worthy," she says, "you must survive all three."',
			narrativeAfter: 'Brigid quenches her latest creation — a blade forged from your trial. "Carry this mark," she says. "It means you have been tested by fire, word, and mercy. Few survive all three."',
			narrativeVictory: 'Fire, word, and mercy — you endure all three aspects of the triple goddess.',
			narrativeDefeat: 'Brigid\'s forge consumes those who are not ready to be remade.',
			aiHeroId: 'hero-tyr', aiHeroClass: 'paladin',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.brigid,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Brigid has 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Brigid channels triple power (+2 mana)' },
			],
			prerequisiteIds: ['celtic-8'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 3250 }],
			campaignArmy: { king: 'king-surtr', queen: 'hero-sol', rook: 'hero-tyr', bishop: 'hero-eir', knight: 'hero-apollo' },
		},
		{
			id: 'celtic-10', chapterId: 'celtic', missionNumber: 10,
			name: 'Lugh of the Long Arm',
			description: 'The master of all arts faces you in final combat.',
			narrativeBefore: 'Lugh Lamhfhada — Lugh of the Long Arm, master of every skill, every craft, every art of war. He slew Balor with a sling-stone. He led the Tuatha De Danann to victory. He is warrior, smith, harper, poet, sorcerer, and champion all in one. "I have mastered everything," he says, his spear Areadbhar blazing with light. "Can you master me?"',
			narrativeAfter: 'Lugh plants his spear and kneels — not in defeat, but in respect. "You have earned something no one has earned in my memory: my acknowledgment that you are my equal." The Otherworld shimmers and the mists of Tir na nOg lift. The Celtic chapter is complete.',
			narrativeVictory: 'The master of all arts concedes. In the annals of the Otherworld, your name is written beside Lugh\'s.',
			narrativeDefeat: 'Lugh is the master of everything — including the art of victory.',
			aiHeroId: 'hero-baldur', aiHeroClass: 'paladin',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.lugh,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Lugh has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Lugh wields all arts (+2 mana)' },
				{ type: 'bonus_draw', value: 1, description: 'Lugh draws from mastery of all crafts' },
			],
			prerequisiteIds: ['celtic-9'],
			rewards: [{ type: 'rune', amount: 100 }, { type: 'card', cardId: 3300 }, { type: 'pack', amount: 2 }],
			campaignArmy: { king: 'king-borr', queen: 'hero-odin', rook: 'hero-thor', bishop: 'hero-freya', knight: 'hero-loki' },
		},
	],
};
