import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const x = (n: number) => 1000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => x(base + (j % 15)));

export const easternChapter: CampaignChapter = {
	id: 'eastern',
	name: 'The Celestial Gate: Myths Beyond the Veil',
	faction: 'eastern',
	description: 'Beyond the myths of the West lies an ancient truth. Chinese, Japanese, and Hindu gods await those who proved worthy across all four realms.',
	chapterReward: [{ type: 'pack', amount: 5 }, { type: 'rune', amount: 500 }],
	missions: [
		{
			id: 'eastern-1', chapterId: 'eastern', missionNumber: 1,
			name: 'The Dragon Gate',
			description: 'A celestial dragon guards the threshold between worlds.',
			narrativeBefore: 'The waterfall roars where heaven meets earth. A carp that swims against the current to the top becomes a dragon — the Dragon Gate. But you are no carp. You are a conqueror of four mythologies, and the dragon that guards this gate knows it. It descends from the clouds, scales like liquid jade, eyes older than the mountains.',
			narrativeAfter: 'The dragon coils around the waterfall and bows its great head. "You have crossed the Dragon Gate," it rumbles. "Few from the Western myths have ever reached this far."',
			narrativeVictory: 'The dragon yields. The gate between worlds swings open.',
			narrativeDefeat: 'The waterfall crashes down. The Dragon Gate remains closed to you.',
			aiHeroId: 'hero-thorgrim', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.hard,
			bossRules: [{ type: 'extra_health', value: 10, description: 'The Dragon has 110 health' }],
			prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 50 }],
			campaignArmy: { king: 'king-brimir', queen: 'hero-fujin', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-2', chapterId: 'eastern', missionNumber: 2,
			name: 'Amaterasu\'s Dawn',
			description: 'The Japanese sun goddess emerges from her cave to judge the intruder.',
			narrativeBefore: 'The world has been dark since Amaterasu retreated into Ama-no-Iwato. The other gods danced and laughed to lure her out, and when she emerged, light returned to Japan. Now she turns that blinding radiance upon you. "You carry the shadows of Western gods," she says, her light burning away pretense. "Show me what remains when all shadow is stripped away."',
			narrativeAfter: 'Amaterasu dims her radiance to something bearable. "There is light in you that no shadow could hide," she says. "You may walk my lands."',
			narrativeVictory: 'You endure the purest light in existence. Amaterasu sees your true nature — and approves.',
			narrativeDefeat: 'The sun\'s full radiance unmakes every shadow you hid behind.',
			aiHeroId: 'hero-shu', aiHeroClass: 'mage',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.amaterasu,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Amaterasu has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Divine solar energy (+1 mana)' },
			],
			prerequisiteIds: ['eastern-1'],
			rewards: [{ type: 'rune', amount: 55 }],
			campaignArmy: { king: 'king-audumbla', queen: 'hero-sol', rook: 'hero-baldur', bishop: 'hero-kamimusubi', knight: 'hero-apollo' },
		},
		{
			id: 'eastern-3', chapterId: 'eastern', missionNumber: 3,
			name: 'The Jade Emperor\'s Court',
			description: 'The ruler of Heaven in Chinese mythology holds court — and you are summoned.',
			narrativeBefore: 'The Jade Palace shimmers above the clouds, its halls of pure jade stretching beyond mortal sight. The Jade Emperor sits upon his throne, surrounded by celestial bureaucrats who manage every aspect of the mortal world. "You have defeated the gods of four lands," he says, checking a celestial ledger. "That is... irregular. We must rectify this."',
			narrativeAfter: 'The Jade Emperor stamps his celestial seal. "Irregular, but... acceptable," he says. "Your file has been updated. You may proceed."',
			narrativeVictory: 'Even heavenly bureaucracy bows to undeniable merit.',
			narrativeDefeat: 'The celestial bureaucracy finds you wanting. Your paperwork is denied.',
			aiHeroId: 'hero-hoenir', aiHeroClass: 'priest',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.jadeEmperor,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'The Jade Emperor has 110 health' },
				{ type: 'bonus_draw', value: 1, description: 'Celestial bureaucracy grants extra resources' },
			],
			prerequisiteIds: ['eastern-2'],
			rewards: [{ type: 'rune', amount: 60 }],
			campaignArmy: { king: 'king-borr', queen: 'hero-odin', rook: 'hero-heimdall', bishop: 'hero-hera', knight: 'hero-hermes' },
		},
		{
			id: 'eastern-4', chapterId: 'eastern', missionNumber: 4,
			name: 'Susanoo\'s Storm',
			description: 'The Japanese storm god unleashes typhoon fury.',
			narrativeBefore: 'Susanoo was banished from heaven for his destruction. He who slew the eight-headed serpent Yamata no Orochi now turns that storm-fury upon you. Rain slashes horizontally. Lightning strikes in sheets. The very ground dissolves into mud. "I was cast out of heaven!" he roars. "Do you think I fear anything?"',
			narrativeAfter: 'Susanoo\'s storm breaks. He stands in the rain, breathing heavily. "You\'re different from the Western gods I\'ve heard about," he says. "They rely on power. You rely on will."',
			narrativeVictory: 'The storm god\'s fury breaks against your resolve like waves on stone.',
			narrativeDefeat: 'No mortal can stand against the fury of heaven\'s exile.',
			aiHeroId: 'hero-ran', aiHeroClass: 'shaman',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.susanoo,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Susanoo has 110 health' },
				{ type: 'passive_damage', value: 1, description: 'Typhoon deals 1 damage each turn' },
			],
			prerequisiteIds: ['eastern-3'],
			rewards: [{ type: 'rune', amount: 65 }, { type: 'eitr', amount: 100 }],
			campaignArmy: { king: 'king-surtr', queen: 'hero-fujin', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-5', chapterId: 'eastern', missionNumber: 5,
			name: 'Monkey King\'s Challenge',
			description: 'Sun Wukong, the Monkey King, challenges you with impossible tricks.',
			narrativeBefore: 'A golden-furred figure somersaults down from a cloud, his Ruyi Jingu Bang staff extending to impossible lengths. Sun Wukong, the Monkey King — who fought the armies of heaven, who was trapped under a mountain for 500 years by the Buddha himself. He grins with monkey mischief. "I can transform 72 ways," he boasts. "I can fly 108,000 li in a single somersault. Beat that."',
			narrativeAfter: 'Sun Wukong scratches his head. "Huh. Not bad for someone who can\'t even somersault on clouds." He shrinks his staff to the size of a needle and tucks it behind his ear. "You\'re alright."',
			narrativeVictory: 'The irrepressible Monkey King is impressed. That alone is worth a legend.',
			narrativeDefeat: 'Sun Wukong laughs and does a backflip. "Too slow! Way too slow!"',
			aiHeroId: 'hero-gormr', aiHeroClass: 'rogue',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.sunWukong,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Sun Wukong has 115 health' },
				{ type: 'bonus_draw', value: 1, description: '72 transformations grant extra cards' },
			],
			prerequisiteIds: ['eastern-4'],
			rewards: [{ type: 'rune', amount: 70 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-loki', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-loki' },
		},
		{
			id: 'eastern-6', chapterId: 'eastern', missionNumber: 6,
			name: 'Izanami\'s Underworld',
			description: 'The mother of Japan waits in Yomi, the land of the dead.',
			narrativeBefore: 'Yomi is darker than any underworld you have visited. Izanami, mother of Japan, died giving birth to fire. Her husband Izanagi came to rescue her but fled when he saw her rotting form. She has not forgiven him — or any living thing — since. "You have visited many underworlds," she says. "This one will be your last."',
			narrativeAfter: 'Izanami retreats into the deepest dark. "Go," she whispers. "But remember: I kill a thousand living things each day in revenge. You are merely the one who got away."',
			narrativeVictory: 'You escape Yomi intact. Izanami\'s curse passes over you — this time.',
			narrativeDefeat: 'Yomi closes around you. Izanami collects another soul for her endless grief.',
			aiHeroId: 'hero-izanami', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.izanami,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Izanami has 115 health' },
				{ type: 'passive_damage', value: 2, description: 'Yomi\'s decay deals 2 damage each turn' },
			],
			prerequisiteIds: ['eastern-5'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 1400 }],
			campaignArmy: { king: 'king-tartarus', queen: 'hero-izanami', rook: 'hero-vidar', bishop: 'hero-ran', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-7', chapterId: 'eastern', missionNumber: 7,
			name: 'Ganesha\'s Puzzle',
			description: 'The elephant-headed god of wisdom presents an impossible riddle.',
			narrativeBefore: 'Ganesha sits cross-legged, his elephant head tilted thoughtfully. The Remover of Obstacles and the Placer of Obstacles — it depends on whether you are worthy. "I will set before you a puzzle," he says, holding up one of his four hands. "It cannot be solved by force, only by understanding. The Western gods rely on strength. Let us see if you have anything else."',
			narrativeAfter: 'Ganesha trumpets with joy. "Beautiful! You did not try to smash through it!" He hands you a golden tusk. "Carry this. It means you think before you strike."',
			narrativeVictory: 'Wisdom overcomes obstacles. Ganesha removes every barrier before you.',
			narrativeDefeat: 'Ganesha sighs. "You think like a warrior. Come back when you think like a sage."',
			aiHeroId: 'hero-frey', aiHeroClass: 'priest',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.ganesha,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Ganesha has 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Divine wisdom grants +2 mana' },
			],
			prerequisiteIds: ['eastern-6'],
			rewards: [{ type: 'rune', amount: 80 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-odin', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-hermes' },
		},
		{
			id: 'eastern-8', chapterId: 'eastern', missionNumber: 8,
			name: 'The Churning of the Ocean',
			description: 'Gods and demons churn the cosmic ocean to create the elixir of immortality.',
			narrativeBefore: 'Mount Mandara spins in the cosmic ocean, Vasuki the serpent wrapped around it as a churning rope. Gods pull one end, demons the other. From the churning emerge wonders and terrors — the moon, divine weapons, deadly poison, and finally the Amrita: the nectar of immortality. Both sides want it. You stand in the middle of a cosmic tug-of-war.',
			narrativeAfter: 'The churning stops. The Amrita glows in its vessel, and you have earned a single sip. Immortality touches your lips — not forever, but long enough to face what comes next.',
			narrativeVictory: 'You stand between gods and demons and claim the Amrita. Both sides are impressed.',
			narrativeDefeat: 'The cosmic ocean swallows you. The churning continues without you.',
			aiHeroId: 'hero-gefjon', aiHeroClass: 'shaman',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.boss,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Cosmic forces have 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Cosmic energy grants +2 mana' },
				{ type: 'bonus_draw', value: 1, description: 'The churning produces extra resources' },
			],
			prerequisiteIds: ['eastern-7'],
			rewards: [{ type: 'rune', amount: 85 }, { type: 'eitr', amount: 150 }],
			campaignArmy: { king: 'king-brimir', queen: 'hero-fujin', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-9', chapterId: 'eastern', missionNumber: 9,
			name: 'Kali\'s Dance of Destruction',
			description: 'The Hindu goddess of time and death dances the world toward its end.',
			narrativeBefore: 'Kali dances. Each step destroys a universe. Each spin creates a new one. She is black as the void between stars, wearing a garland of skulls, her tongue red with the blood of demons. She is Time itself, and Time destroys everything. "Dance with me," she says, her wild eyes burning. "If you can keep up, you live. If not..." She laughs, and galaxies tremble.',
			narrativeAfter: 'Kali stops dancing. The silence is deafening. "You... kept up," she says, genuinely surprised. "No one has ever kept up." She removes one skull from her necklace. "Take this. It belonged to a god who thought he was stronger than Time. You are wiser."',
			narrativeVictory: 'You dance with destruction itself and survive. Kali keeps time — and you kept pace.',
			narrativeDefeat: 'Time dances on. You do not.',
			aiHeroId: 'hero-dionysus', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.kali,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Kali has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Time\'s power grants +2 mana' },
				{ type: 'passive_damage', value: 2, description: 'Kali\'s dance deals 2 damage each turn' },
			],
			prerequisiteIds: ['eastern-8'],
			rewards: [{ type: 'rune', amount: 90 }, { type: 'card', cardId: 1450 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-izanami', rook: 'hero-logi', bishop: 'hero-ran', knight: 'hero-nyx' },
		},
		{
			id: 'eastern-10', chapterId: 'eastern', missionNumber: 10,
			name: 'Ragnarok of All Worlds',
			description: 'Every mythology collides. The final battle for all creation.',
			narrativeBefore: 'The barriers between mythologies shatter. Norse, Greek, Egyptian, Celtic, Chinese, Japanese, Hindu — every pantheon\'s apocalypse arrives simultaneously. Ragnarok. Gigantomachy. The devouring of Ra. The final Fomorian war. The celestial collapse. They all happen at once, in the same place, and at the center of it all stands the adversary: a being woven from every mythology\'s concept of the End. "You conquered each pantheon separately," it speaks with a thousand voices. "Now face them all at once."',
			narrativeAfter: 'Silence. For the first time in the history of every mythology, the End was met — and turned back. The being of endings unravels, and from its dissolution, new stories begin. You stand at the nexus of all myths, the one who prevented the final Ragnarok. Every god, from every pantheon, knows your name. The campaign is complete.',
			narrativeVictory: 'You are the champion of all mythologies. The one who stood at the end of everything and said: "Not today." Every god across every pantheon bows.',
			narrativeDefeat: 'All endings arrive at once. But even this is just a story — and stories can be retold.',
			aiHeroId: 'hero-hyperion', aiHeroClass: 'mage',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.boss,
			bossRules: [
				{ type: 'extra_health', value: 30, description: 'The World-Ender has 130 health' },
				{ type: 'extra_mana', value: 3, description: 'All mythologies\' power combined (+3 mana)' },
				{ type: 'bonus_draw', value: 2, description: 'Draws from every pantheon\'s arsenal' },
				{ type: 'passive_damage', value: 2, description: 'The unraveling deals 2 damage each turn' },
			],
			prerequisiteIds: ['eastern-9'],
			rewards: [{ type: 'rune', amount: 200 }, { type: 'card', cardId: 1500 }, { type: 'pack', amount: 5 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-zeus', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-loki' },
		},
	],
};
