import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const e = (n: number) => 2000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => e(base + (j % 15)));

export const egyptianChapter: CampaignChapter = {
	id: 'egyptian',
	name: 'Duat: Shadows of the Pharaohs',
	faction: 'egyptian',
	description: 'Traverse the Egyptian underworld and face the judgment of the gods who weigh the hearts of mortals.',
	chapterReward: [{ type: 'pack', amount: 3 }, { type: 'rune', amount: 200 }],
	missions: [
		{
			id: 'egyptian-1', chapterId: 'egyptian', missionNumber: 1,
			name: 'The Scarab\'s Awakening',
			description: 'Khepri, the dawn scarab, tests those who enter the Duat at sunrise.',
			narrativeBefore: 'The first light of Ra splits the horizon as a massive scarab beetle rolls the sun itself across the sky. Khepri, god of the dawn, clicks his mandibles in challenge. "None pass into the Duat without proving they can endure the light of truth."',
			narrativeAfter: 'Khepri folds his wings and bows. "The dawn accepts you. Walk further into the land of the dead — if you dare."',
			narrativeVictory: 'The scarab of dawn is impressed. You carry the light of the living into the realm of the dead.',
			narrativeDefeat: 'Khepri clicks disapprovingly. The dawn rejects you.',
			aiHeroId: 'egyptian-hunter-1', aiHeroClass: 'hunter',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 20 }],
			campaignArmy: { king: 'king-gaia', queen: 'hero-shu', rook: 'hero-baldur', bishop: 'hero-maat', knight: 'hero-khepri' },
		},
		{
			id: 'egyptian-2', chapterId: 'egyptian', missionNumber: 2,
			name: 'Sands of the Scorpion',
			description: 'Serqet\'s desert trial — her venom tests the worthy.',
			narrativeBefore: 'The desert stretches endlessly. Serqet appears from the sand itself, her scorpion tail arched and dripping venom. "My poison separates the weak from the strong," she hisses. "Which are you?"',
			narrativeAfter: 'Serqet withdraws her stinger. "Your blood is strong enough to resist my venom."',
			narrativeVictory: 'The scorpion goddess\'s poison could not reach your heart.',
			narrativeDefeat: 'Serqet\'s venom courses through you. The desert claims another.',
			aiHeroId: 'egyptian-rogue-2', aiHeroClass: 'rogue',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: ['egyptian-1'],
			rewards: [{ type: 'rune', amount: 25 }],
			campaignArmy: { king: 'king-gaia', queen: 'hero-ammit', rook: 'hero-hephaestus', bishop: 'hero-maat', knight: 'hero-serqet' },
		},
		{
			id: 'egyptian-3', chapterId: 'egyptian', missionNumber: 3,
			name: 'The Weighing of Hearts',
			description: 'Ma\'at weighs your heart against the Feather of Truth.',
			narrativeBefore: 'The Hall of Two Truths stretches before you. Ma\'at stands beside her golden scales, the feather of truth resting on one side. "Place your heart on the scales," she commands. "If it is heavier than my feather, Ammit devours it."',
			narrativeAfter: 'The scales balance. Ma\'at nods. "Your heart is true. But the deeper Duat will test more than your virtue."',
			narrativeVictory: 'Your heart balances against truth itself. Few mortals pass this judgment.',
			narrativeDefeat: 'The scales tip. Your heart is heavier than truth.',
			aiHeroId: 'egyptian-priest-3', aiHeroClass: 'priest',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.maat,
			bossRules: [{ type: 'bonus_draw', value: 1, description: 'Ma\'at draws wisdom from the scales' }],
			prerequisiteIds: ['egyptian-2'],
			rewards: [{ type: 'rune', amount: 30 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-shu', rook: 'hero-heimdall', bishop: 'hero-maat', knight: 'hero-khepri' },
		},
		{
			id: 'egyptian-4', chapterId: 'egyptian', missionNumber: 4,
			name: 'The Devourer Awaits',
			description: 'Ammit hungers for the unworthy.',
			narrativeBefore: 'Behind Ma\'at\'s scales lurks Ammit — part crocodile, part lion, part hippopotamus. She has devoured the hearts of millions. Her jaws open wide. "Your heart passed the scales," she growls. "But I am still hungry."',
			narrativeAfter: 'Ammit snaps her jaws on empty air. "Go then. But I wait at the end of all things."',
			narrativeVictory: 'The Devourer goes hungry. Your soul is too fierce to be swallowed.',
			narrativeDefeat: 'Ammit\'s jaws close. Another soul devoured.',
			aiHeroId: 'egyptian-warrior-4', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.ammit,
			bossRules: [{ type: 'extra_health', value: 5, description: 'Ammit has 105 health' }],
			prerequisiteIds: ['egyptian-3'],
			rewards: [{ type: 'rune', amount: 35 }, { type: 'eitr', amount: 50 }],
			campaignArmy: { king: 'king-tartarus', queen: 'hero-ammit', rook: 'hero-ares', bishop: 'hero-aphrodite', knight: 'hero-serqet' },
		},
		{
			id: 'egyptian-5', chapterId: 'egyptian', missionNumber: 5,
			name: 'Storms of Set',
			description: 'The god of chaos unleashes the desert storm.',
			narrativeBefore: 'The sky turns crimson as Set, the red god of chaos, rises like a sandstorm given flesh. He murdered Osiris. He fights Apophis each night. "Order is a lie," he roars. "Let me show you the truth."',
			narrativeAfter: 'Set dissolves into sand and wind. "Chaos cannot be defeated. But you have earned its... respect."',
			narrativeVictory: 'You stand firm in the eye of chaos. Set\'s storm cannot uproot you.',
			narrativeDefeat: 'The desert storm swallows you whole.',
			aiHeroId: 'egyptian-warlock-5', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.set,
			bossRules: [
				{ type: 'extra_health', value: 5, description: 'Set has 105 health' },
				{ type: 'passive_damage', value: 1, description: 'Sandstorm deals 1 damage each turn' },
			],
			prerequisiteIds: ['egyptian-4'],
			rewards: [{ type: 'rune', amount: 40 }],
			campaignArmy: { king: 'king-surtr', queen: 'hero-ammit', rook: 'hero-logi', bishop: 'hero-poseidon', knight: 'hero-serqet' },
		},
		{
			id: 'egyptian-6', chapterId: 'egyptian', missionNumber: 6,
			name: 'The Sun Barge',
			description: 'Journey with Ra through the twelve hours of night.',
			narrativeBefore: 'Ra\'s golden barge sails the sky of the Duat, carrying the sun through the underworld. Each hour brings new terrors. Ra sits at the prow, ancient and blazing. You must protect the sun through the darkest hour or dawn will never come.',
			narrativeAfter: 'The twelfth hour passes and the eastern horizon glows gold. Ra nods. "You have kept the light alive."',
			narrativeVictory: 'Dawn breaks because of you. Ra will remember.',
			narrativeDefeat: 'The serpents overwhelm the barge. For the first time, dawn is delayed.',
			aiHeroId: 'egyptian-mage-6', aiHeroClass: 'mage',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.ra,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Ra has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Ra channels solar energy (+1 mana)' },
			],
			prerequisiteIds: ['egyptian-5'],
			rewards: [{ type: 'rune', amount: 50 }, { type: 'card', cardId: 2200 }],
			campaignArmy: { king: 'king-audumbla', queen: 'hero-shu', rook: 'hero-baldur', bishop: 'hero-hestia', knight: 'hero-apollo' },
		},
		{
			id: 'egyptian-7', chapterId: 'egyptian', missionNumber: 7,
			name: 'Tears of Isis',
			description: 'The goddess of magic weaves spells beyond mortal comprehension.',
			narrativeBefore: 'Isis stands wreathed in enchantments that shimmer like the Nile at midnight. She reassembled Osiris, tricked Ra into revealing his true name. "I have wept an ocean of tears," she says. "Can you endure what made a goddess cry?"',
			narrativeAfter: 'Isis lowers her hands. "You have more strength than I expected. Use it wisely."',
			narrativeVictory: 'The greatest sorceress in creation acknowledges your power.',
			narrativeDefeat: 'Isis\'s enchantments weave around you like chains.',
			aiHeroId: 'egyptian-mage-7', aiHeroClass: 'mage',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.isis,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Isis has 110 health' },
				{ type: 'bonus_draw', value: 1, description: 'Isis weaves extra cards from magic' },
			],
			prerequisiteIds: ['egyptian-6'],
			rewards: [{ type: 'rune', amount: 55 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-sol', rook: 'hero-tyr', bishop: 'hero-freya', knight: 'hero-hermes' },
		},
		{
			id: 'egyptian-8', chapterId: 'egyptian', missionNumber: 8,
			name: 'Anubis\' Gauntlet',
			description: 'The jackal-headed god of death guides or condemns you.',
			narrativeBefore: 'Anubis waits in the deepest chamber, his jackal eyes seeing through every lie. "I have prepared billions for their final journey," he says. "You are not dead yet. That makes this... interesting."',
			narrativeAfter: 'Anubis wraps you in bandages that dissolve into golden light. "You have been judged worthy."',
			narrativeVictory: 'The judge of the dead finds you worthy of the living.',
			narrativeDefeat: 'Anubis wraps you in burial cloth. Your journey ends here.',
			aiHeroId: 'egyptian-priest-8', aiHeroClass: 'priest',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.anubis,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Anubis has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Anubis channels death energy (+1 mana)' },
			],
			prerequisiteIds: ['egyptian-7'],
			rewards: [{ type: 'rune', amount: 60 }, { type: 'eitr', amount: 100 }],
			campaignArmy: { king: 'king-tartarus', queen: 'hero-hel', rook: 'hero-vidar', bishop: 'hero-maat', knight: 'hero-nyx' },
		},
		{
			id: 'egyptian-9', chapterId: 'egyptian', missionNumber: 9,
			name: 'The Serpent Apophis',
			description: 'The chaos serpent threatens to devour the sun forever.',
			narrativeBefore: 'In the deepest abyss, Apophis coils — the serpent of chaos, older than creation itself. Each night it tries to swallow Ra\'s barge. Its body stretches beyond sight, scales blacker than the void. If it wins, the sun dies.',
			narrativeAfter: 'Apophis shrieks and retreats into the abyss. But it will return tomorrow, as it always has.',
			narrativeVictory: 'Chaos itself recoils. The sun will rise because you stood firm.',
			narrativeDefeat: 'Apophis swallows the light. The sun goes dark.',
			aiHeroId: 'egyptian-boss-9', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.apophis,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Apophis has 115 health' },
				{ type: 'passive_damage', value: 2, description: 'Apophis\' darkness deals 2 damage each turn' },
			],
			prerequisiteIds: ['egyptian-8'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 2250 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-hades', rook: 'hero-logi', bishop: 'hero-ran', knight: 'hero-nyx' },
		},
		{
			id: 'egyptian-10', chapterId: 'egyptian', missionNumber: 10,
			name: 'Throne of the Pharaoh',
			description: 'Osiris renders final judgment from his eternal throne.',
			narrativeBefore: 'Osiris sits upon the Throne of the Dead, green-skinned and wrapped in white. He who died and was reborn. "I have waited," he says. "Every soul that passed through my realm spoke of you. Now I will see for myself."',
			narrativeAfter: 'Osiris rises from his throne for the first time in millennia. "You have walked through the entire Duat and emerged unbroken. When your time truly comes, you will sit at my right hand." The chapter of Egypt is complete.',
			narrativeVictory: 'The Lord of the Dead is defeated. You have conquered death\'s own kingdom.',
			narrativeDefeat: 'Osiris shakes his head slowly. "Not yet. But you will return."',
			aiHeroId: 'egyptian-boss-10', aiHeroClass: 'priest',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.osiris,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Osiris has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Osiris wields death\'s power (+2 mana)' },
				{ type: 'bonus_draw', value: 1, description: 'Osiris draws from the Book of the Dead' },
			],
			prerequisiteIds: ['egyptian-9'],
			rewards: [{ type: 'rune', amount: 100 }, { type: 'card', cardId: 2300 }, { type: 'pack', amount: 2 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-hel', rook: 'hero-tyr', bishop: 'hero-maat', knight: 'hero-khepri' },
		},
	],
};
