import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const g = (n: number) => 20000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => g(base + (j % 15)));

export const greekChapter: CampaignChapter = {
	id: 'greek',
	name: 'Echoes of Chaos: Blood of the Olympians',
	faction: 'greek',
	description: 'From the yawning void of Chaos to the fall of the Titans and the rise of Olympus — witness the Theogony unfold. Hesiod\'s cosmogony, Apollodorus\' wars, and the blood of gods spilled across every age.',
	chapterReward: [{ type: 'pack', amount: 3 }, { type: 'rune', amount: 200 }],
	cinematicIntro: {
		title: 'Blood of the Olympians',
		style: 'Greek vase-painting art style transitioning to cinematic CGI — sweeping aerial shots, marble and bronze, orchestral score with lyres, war drums, and Homeric chanting. 3:00 runtime. Ancient, measured narrator.',
		scenes: [
			{
				narration: 'In the beginning there was only Chaos — the yawning void, boundless and formless. From this emptiness, the first powers stirred: Gaia, broad-breasted Earth. Tartarus, the pit beneath all things. And Eros, the force that compels creation itself.',
				visualCue: 'Infinite darkness. Slowly, a vast earthen form takes shape — Gaia rising, mountains forming along her spine. Below, an abyss glows with dull red fire. Golden threads of Eros weave between them.',
				musicCue: 'Single sustained lyre note. Growing harmonic overtones.',
				durationHint: 15,
			},
			{
				narration: 'From Gaia came Uranus — the starry sky — and he covered her utterly. Together they spawned the Titans: twelve colossal gods of the first age. But Uranus feared his own children. The Cyclopes, the Hundred-Handers — he thrust them back into Gaia\'s womb, into the darkness of Tartarus.',
				visualCue: 'Star-crowned Uranus descends over Gaia. Twelve enormous Titan figures stand in a circle. Then chains of sky-metal bind the Cyclopes and Hecatonchires, dragging them screaming underground. Gaia writhes in agony.',
				musicCue: 'Ominous brass. Chains rattling. Distant screaming.',
				durationHint: 14,
			},
			{
				narration: 'Gaia\'s grief became rage. She forged a great sickle of grey adamant and whispered to her children: "Avenge me." Only Cronus, youngest of the Titans, dared answer. He took the sickle. He waited in ambush. And when Uranus came to lie with Earth... Cronus cut him from the sky.',
				visualCue: 'Close-up: jagged adamant sickle gleaming. Cronus crouches in shadow. Uranus descends — a flash of the blade. Blood rains down, birthing the Furies from the earth, Aphrodite from the sea-foam. Uranus screams and recoils into the heavens forever.',
				musicCue: 'Thunderous percussion. Choir rises to crescendo.',
				durationHint: 16,
			},
			{
				narration: 'So began the age of the Titans — and so would it end. For Cronus learned that his own children would overthrow him, just as he had overthrown his father. The cycle of blood was set. The Theogony had begun.',
				visualCue: 'Cronus on a golden throne, eyes haunted. He raises a swaddled infant to his mouth. Camera pulls back to reveal Mount Othrys towering above the world. Storm clouds gather on the horizon.',
				musicCue: 'Low war drums. Fade to silence.',
				durationHint: 12,
			},
		],
	},
	missions: [
		{
			id: 'greek-1', chapterId: 'greek', missionNumber: 1,
			name: 'From the Void',
			description: 'Chaos births the first powers. Survive the primordial darkness where Erebus and Nyx hold dominion.',
			narrativeBefore: 'Before earth, before sky, before time — there was only Chaos. The void writhes with formless potential. From this emptiness Erebus, the darkness absolute, and Nyx, mother of night, have spawned their terrible children. You are a spark of Eros\'s will, the first force of creation, thrust into the void to kindle order from nothing. The darkness does not welcome you.',
			narrativeAfter: 'Light pierces the void for the first time. Erebus recoils into the deep places, and Nyx retreats to her cavern at the edge of the world. Gaia stirs beneath your feet — the Earth is waking.',
			narrativeVictory: 'Even the primordial dark must yield to the first light. Creation has begun.',
			narrativeDefeat: 'The void closes around you. Chaos swallows what it birthed. There was never anything here at all.',
			aiHeroId: 'hero-nyx', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 20 }],
			realm: 'chaos',
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-nyx', rook: 'hero-hades', bishop: 'hero-demeter', knight: 'hero-hermes' },
		},
		{
			id: 'greek-2', chapterId: 'greek', missionNumber: 2,
			name: 'The Sky Tyrant',
			description: 'Uranus, the starry sky, imprisons his monstrous children in Gaia\'s depths. End his tyranny.',
			narrativeBefore: 'Uranus stretches across the heavens, vast and pitiless. His children — the one-eyed Cyclopes, the hundred-handed Hecatonchires — scream in the darkness of Tartarus where he has imprisoned them. Gaia groans under the weight of sky and sorrow. She has forged a sickle of grey adamant. Someone must wield it. "Avenge me," she whispers through the stone. "Cut the tyrant from my back."',
			narrativeAfter: 'The sky recoils. Uranus\'s blood rains upon the earth, and from it spring the Erinyes — the Furies, avengers of blood-crime forevermore. From the foam where his severed flesh meets the sea, Aphrodite rises, terrible and beautiful. The first age ends in blood, as all ages must.',
			narrativeVictory: 'The sky-father falls. His own cruelty was the sickle that unmade him.',
			narrativeDefeat: 'Uranus presses down. The earth is sealed. The children will scream in the dark forever.',
			aiHeroId: 'hero-hyperion', aiHeroClass: 'mage',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.uranus,
			bossRules: [{ type: 'passive_damage', value: 1, description: 'Uranus\'s crushing sky deals 1 damage each turn' }],
			prerequisiteIds: ['greek-1'],
			rewards: [{ type: 'rune', amount: 25 }],
			realm: 'gaia_earth',
			campaignArmy: { king: 'king-uranus', queen: 'hero-hyperion', rook: 'hero-ares', bishop: 'hero-hera', knight: 'hero-apollo' },
		},
		{
			id: 'greek-3', chapterId: 'greek', missionNumber: 3,
			name: 'The Golden Devourer',
			description: 'Cronus rules the golden age — and swallows his own children to cheat the prophecy.',
			narrativeBefore: 'Cronus sits upon the golden throne of Othrys, lord of all Titans. The age of gold has dawned — mortals live without toil, the earth yields freely, and death comes only as gentle sleep. But Cronus knows the prophecy: his own child shall overthrow him, as he overthrew Uranus. So when Rhea bears him children — Hestia, Demeter, Hera, Hades, Poseidon — he swallows each one whole. His eyes are wild. His hands shake. The golden age rots from within.',
			narrativeAfter: 'Cronus clutches his belly too late. The emetic takes hold. He vomits forth five immortal gods — full-grown, furious, and free. Zeus stands among them, thunder already gathering in his fists. The golden throne cracks down the middle.',
			narrativeVictory: 'Even a god who devours fate cannot escape it. The children always rise.',
			narrativeDefeat: 'Cronus\'s jaws close. Another child, another swallowed future. The prophecy sleeps on.',
			aiHeroId: 'hero-chronos', aiHeroClass: 'mage',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.kronos,
			bossRules: [{ type: 'extra_health', value: 5, description: 'Cronus has 105 health from Titan constitution' }],
			prerequisiteIds: ['greek-2'],
			rewards: [{ type: 'rune', amount: 30 }],
			realm: 'mount_othrys',
			campaignArmy: { king: 'king-surtr', queen: 'hero-chronos', rook: 'hero-hephaestus', bishop: 'hero-demeter', knight: 'hero-hermes' },
		},
		{
			id: 'greek-4', chapterId: 'greek', missionNumber: 4,
			name: 'The Forge of Thunder',
			description: 'Descend to Tartarus. Free the Cyclopes. Forge the weapons that will end the Titan age.',
			narrativeBefore: 'Zeus descends into the abyss. Tartarus — where Uranus imprisoned the Cyclopes and Hecatonchires ages ago. They languish still in chains of sky-metal, their forge-fires cold. Brontes, Steropes, Arges — one-eyed smiths of impossible craft. "Free us," Brontes rumbles, his single eye dim, "and we will forge you weapons no Titan can withstand." But Tartarus has a jailer: Campe, the she-dragon, set by Cronus to guard what Uranus locked away.',
			narrativeAfter: 'Campe\'s serpentine corpse dissolves into shadow. The chains shatter. The Cyclopes rise, their forge-fires blazing white. From the heart of the earth they draw thunderbolts for Zeus, a trident for Poseidon, a helm of invisibility for Hades. The weapons of the Olympians are born in Tartarus\'s dark.',
			narrativeVictory: 'The jailer falls. Three forges roar to life. Heaven will tremble at what they craft.',
			narrativeDefeat: 'Campe\'s coils tighten. The Cyclopes will never see the sky again.',
			aiHeroId: 'hero-hephaestus', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.medium,
			bossRules: [{ type: 'start_with_minion', cardId: 20203, description: 'Campe starts with a guardian serpent on the battlefield' }],
			prerequisiteIds: ['greek-3'],
			rewards: [{ type: 'rune', amount: 35 }, { type: 'eitr', amount: 50 }],
			realm: 'tartarus',
			campaignArmy: { king: 'king-tartarus', queen: 'hero-hephaestus', rook: 'hero-ares', bishop: 'hero-poseidon', knight: 'hero-hermes' },
		},
		{
			id: 'greek-5', chapterId: 'greek', missionNumber: 5,
			name: 'Titanomachy',
			description: 'The ten-year war. Storm Mount Othrys and break the Titan host forever.',
			narrativeBefore: 'For ten years the cosmos shakes. Olympians hold Mount Olympus; Titans hold Mount Othrys. The Hecatonchires hurl three hundred boulders each volley. Zeus\'s thunderbolts set the world ablaze. The sea boils. Forests burn to ash. Even Tartarus trembles at the violence above. Now comes the final assault: Atlas, mightiest warrior of the Titans, holds the line at Othrys. He must fall, or the war will never end. Hesiod wrote: "The boundless sea roared terribly, the great earth crashed, and broad heaven groaned, shaken." (Theogony 678-681)',
			narrativeAfter: 'Atlas staggers. The Titan line breaks. Zeus\'s thunderbolts crack Othrys in half and the mountain crumbles. One by one the Titans are hurled into Tartarus — bound in chains of bronze behind walls of adamant, with the Hecatonchires standing guard forever. But Atlas receives a crueler sentence: he shall hold the sky upon his shoulders for all eternity.',
			narrativeVictory: 'The Titans fall. Othrys burns. A new order rises on Olympus, built on the bones of the old.',
			narrativeDefeat: 'Atlas holds the line. The Olympians break against Othrys like waves against a cliff.',
			aiHeroId: 'hero-ares', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.atlas,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Atlas has 110 health — mightiest of the Titan warriors' },
				{ type: 'bonus_draw', value: 1, description: 'Atlas rallies Titan reinforcements each turn' },
			],
			prerequisiteIds: ['greek-4'],
			rewards: [{ type: 'rune', amount: 50 }, { type: 'card', cardId: 20209 }],
			realm: 'mount_othrys',
			campaignArmy: { king: 'king-surtr', queen: 'hero-ares', rook: 'hero-hephaestus', bishop: 'hero-athena', knight: 'hero-apollo' },
		},
		{
			id: 'greek-6', chapterId: 'greek', missionNumber: 6,
			name: 'Prometheus\' Gift',
			description: 'Fire is stolen from heaven. Pandora is fashioned from clay. The age of mortals begins in hope and horror.',
			narrativeBefore: 'The war is won. Zeus divides the cosmos — sky for himself, sea for Poseidon, the underworld for Hades. But on the earth below, Prometheus, the far-seeing Titan who sided with Zeus, shapes mortals from clay and water. Athena breathes life into them. They are frail, shivering, helpless in the dark. Prometheus looks to Olympus, where the gods feast by firelight, and makes a choice that will cost him everything. He steals fire from the forge of heaven and carries it to earth in a fennel stalk. Zeus\'s rage is absolute.',
			narrativeAfter: 'The fire crackles in mortal hands. They warm themselves, cook their food, forge their first tools. But Zeus has already commanded Hephaestus to fashion Pandora — the "all-gifted" woman, beautiful and cursed. She carries a jar. When she opens it, every evil flies free: disease, despair, old age, death. Only Hope remains, trapped beneath the lid. The golden age of innocence is over.',
			narrativeVictory: 'Fire burns in mortal hearths. The cost was terrible — but the gift endures.',
			narrativeDefeat: 'The fire goes out. Mortals shiver in eternal darkness, forgotten by the gods.',
			aiHeroId: 'hero-zeus', aiHeroClass: 'mage',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.hard,
			bossRules: [
				{ type: 'extra_health', value: 5, description: 'Zeus\'s wrath grants 105 health' },
				{ type: 'extra_mana', value: 1, description: 'Divine authority grants +1 mana' },
			],
			prerequisiteIds: ['greek-5'],
			rewards: [{ type: 'rune', amount: 45 }],
			realm: 'olympus',
			campaignArmy: { king: 'king-gaia', queen: 'hero-zeus', rook: 'hero-ares', bishop: 'hero-hera', knight: 'hero-hermes' },
		},
		{
			id: 'greek-7', chapterId: 'greek', missionNumber: 7,
			name: 'Typhon, Father of Monsters',
			description: 'Gaia\'s vengeance takes shape. The most terrible creature ever born rises from the earth.',
			narrativeBefore: 'Gaia does not forgive. Her Titan children rot in Tartarus. Her fury takes monstrous form: Typhon, born from her union with Tartarus itself. He is vast beyond comprehension — his head scrapes the stars, serpents writhe from his thighs, fire pours from his eyes. "A hundred dragon-heads grew from his shoulders," Hesiod wrote, "and flame flickered from every jaw." (Theogony 824-828). Even the Olympians flee at the sight of him. Only Zeus stands firm.',
			narrativeAfter: 'Zeus hurls thunderbolt after thunderbolt. The earth melts. Mountains collapse. Typhon\'s serpent-heads char and fall. At last the Father of Monsters crashes down — and Zeus buries him beneath Mount Etna, where his fury still rumbles as volcanic fire. But Typhon\'s children live on: Cerberus, the Hydra, the Chimera, the Sphinx. His legacy is written in monster-blood across the age of heroes.',
			narrativeVictory: 'The earth splits and swallows its own creation. Typhon burns beneath Etna forever.',
			narrativeDefeat: 'Typhon tears the sinews from Zeus\'s limbs. Olympus falls. The age of monsters begins.',
			aiHeroId: 'hero-hades', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.typhon,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Typhon has 115 health — mightiest monster ever born' },
				{ type: 'passive_damage', value: 2, description: 'Typhon\'s hundred dragon-heads deal 2 damage each turn' },
			],
			prerequisiteIds: ['greek-6'],
			rewards: [{ type: 'rune', amount: 55 }, { type: 'eitr', amount: 75 }],
			realm: 'cilicia',
			campaignArmy: { king: 'king-tartarus', queen: 'hero-hades', rook: 'hero-ares', bishop: 'hero-poseidon', knight: 'hero-artemis' },
		},
		{
			id: 'greek-8', chapterId: 'greek', missionNumber: 8,
			name: 'Blood of the Giants',
			description: 'The Gigantomachy erupts. Gaia\'s giants storm Olympus — and only mortal blood can end them.',
			narrativeBefore: 'Gaia\'s rage is inexhaustible. From the blood Uranus spilled upon her long ago, the Giants were born — enormous, armored in gleaming scales, serpent-tailed, hurling flaming oaks at the heavens. Porphyrion leads them, king of giants, and he storms toward Olympus with an army that darkens the sky. But there is a prophecy: the Giants cannot be slain by gods alone. A mortal champion must deal the killing blow. Heracles strings his bow. The final war of the divine age has come.',
			narrativeAfter: 'Heracles\' arrows find their marks. Athena buries Enceladus beneath Sicily. Poseidon breaks Polybotes under a chunk of Kos island. Porphyrion falls last — struck by Zeus\'s thunderbolt and pierced by Heracles\' shaft simultaneously. The Gigantomachy ends. Gaia weeps. The mountains where giants fell become the islands of the Aegean.',
			narrativeVictory: 'Gods and mortals fight as one. The giants become geography — buried beneath the islands they tried to destroy.',
			narrativeDefeat: 'Porphyrion reaches Zeus\'s throne. Olympus crumbles. The age of gods ends in ruin.',
			aiHeroId: 'hero-ares', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.porphyrion,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Porphyrion has 110 health — king of the Giants' },
				{ type: 'extra_mana', value: 1, description: 'Giant fury grants +1 mana' },
				{ type: 'bonus_draw', value: 1, description: 'The giant horde provides endless reinforcements' },
			],
			prerequisiteIds: ['greek-7'],
			rewards: [{ type: 'rune', amount: 65 }, { type: 'card', cardId: 20216 }],
			realm: 'phlegra',
			campaignArmy: { king: 'king-brimir', queen: 'hero-ares', rook: 'hero-hephaestus', bishop: 'hero-poseidon', knight: 'hero-artemis' },
		},
		{
			id: 'greek-9', chapterId: 'greek', missionNumber: 9,
			name: 'The Heroic Age',
			description: 'Demigods walk the earth. Face the labors, the quests, and the monsters that define the age of heroes.',
			narrativeBefore: 'The wars of gods are over. Now comes the age of heroes — mortals with divine blood, cursed to greatness and doomed to tragedy. Heracles endures his twelve labors. Perseus slays Medusa with Athena\'s mirror-shield. Theseus descends into the Labyrinth. Bellerophon rides Pegasus against the Chimera. But the greatest war is yet to come: Troy smolders on the horizon, and Athena has chosen her champion. She tests you now, grey-eyed and pitiless. "Show me," she says, "that you belong among them."',
			narrativeAfter: 'Athena lowers her aegis. "Wisdom and courage together," she says. "You have the makings of a hero." In the distance, a thousand ships are being built. The Trojan War looms — but that story belongs to another age, another song.',
			narrativeVictory: 'The goddess of strategy concedes. Your name will echo alongside Perseus and Heracles.',
			narrativeDefeat: 'Athena predicted every move. The age of heroes has no room for the unworthy.',
			aiHeroId: 'hero-athena', aiHeroClass: 'mage',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.athena,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Athena has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Athena\'s divine wisdom grants +1 mana' },
			],
			prerequisiteIds: ['greek-8'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'eitr', amount: 100 }],
			realm: 'athens',
			campaignArmy: { king: 'king-gaia', queen: 'hero-athena', rook: 'hero-heimdall', bishop: 'hero-hera', knight: 'hero-hermes' },
		},
		{
			id: 'greek-10', chapterId: 'greek', missionNumber: 10,
			name: 'Seeds of Strife',
			description: 'Gaia stirs one final time. Seal the rifts of Tartarus before the primordial mother unmakes everything the gods have built.',
			narrativeBefore: 'The cosmos trembles. Deep in the earth, Gaia — who birthed the sky, the sea, the mountains, the Titans, the Giants, and Typhon — gathers what remains of her strength for one final act. The walls of Tartarus crack. Imprisoned Titans stir in their chains. Primordial forces seep through the rifts: Chaos itself bleeds back into the world. Gaia does not seek victory. She seeks return — to the void before creation, before the violence her children inflicted upon each other for ten thousand years. "I am tired," the earth groans. "Let it all go back to nothing." You stand at the axis of the world. Behind you: Olympus, mortal cities, everything that exists. Before you: the open mouth of the abyss.',
			narrativeAfter: 'The rifts seal. Gaia\'s trembling subsides. The earth settles. The Titans remain bound. Chaos recedes to the edges of existence, where it has always waited. Olympus endures — for now. But the prophecy lingers: Zeus himself shall one day be overthrown, as Uranus was, as Cronus was. The cycle of blood has merely paused. Somewhere in the deep places, something is already beginning to stir.',
			narrativeVictory: 'The axis holds. Creation endures — scarred, bloodied, but unbroken. The Theogony is complete.',
			narrativeDefeat: 'The rifts widen. Tartarus opens. The world returns to Chaos, as Gaia always intended.',
			aiHeroId: 'hero-demeter', aiHeroClass: 'druid',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.gaiaRemnant,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Gaia\'s Remnant has 120 health — primordial endurance' },
				{ type: 'extra_mana', value: 2, description: 'Primordial power grants +2 mana' },
				{ type: 'bonus_draw', value: 1, description: 'The earth yields endless reinforcements' },
			],
			prerequisiteIds: ['greek-9'],
			rewards: [{ type: 'rune', amount: 100 }, { type: 'card', cardId: 20002 }, { type: 'pack', amount: 2 }],
			realm: 'tartarus',
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-demeter', rook: 'hero-poseidon', bishop: 'hero-hades', knight: 'hero-apollo' },
		},
	],
};
