import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const g = (n: number) => 1000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => g(base + (j % 15)));

export const greekChapter: CampaignChapter = {
	id: 'greek',
	name: 'Olympus: Wrath of the Titans',
	faction: 'greek',
	description: 'Ascend Mount Olympus and challenge the Greek pantheon as the Titans stir in Tartarus.',
	chapterReward: [{ type: 'pack', amount: 3 }, { type: 'rune', amount: 200 }],
	missions: [
		{
			id: 'greek-1', chapterId: 'greek', missionNumber: 1,
			name: 'Cerberus Awakens',
			description: 'The three-headed guardian blocks the gates of the Underworld.',
			narrativeBefore: 'The river Styx laps at your feet as you approach the gates of Hades\' domain. Three pairs of burning eyes fix upon you from the darkness. Cerberus, the hound of hell, rises to his full terrible height. There is no path to the Underworld except through him.',
			narrativeAfter: 'Cerberus whimpers and slinks aside, his three heads bowed. The gates of the Underworld groan open. Hades knows you have arrived.',
			narrativeVictory: 'The great hound yields. Even the guardian of the dead recognizes strength when it stands before him.',
			narrativeDefeat: 'Cerberus\' three jaws close around your fate. The Underworld claims another soul before its time.',
			aiHeroId: 'hero-ares', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 20 }],
			realm: 'underworld',
			campaignArmy: { king: 'king-tartarus', queen: 'hero-ammit', rook: 'hero-ares', bishop: 'hero-aphrodite', knight: 'hero-nyx' },
		},
		{
			id: 'greek-2', chapterId: 'greek', missionNumber: 2,
			name: 'The Labyrinth',
			description: 'Navigate Daedalus\' deadly maze and face the Minotaur within.',
			narrativeBefore: 'The walls of the Labyrinth shift and groan like a living thing. Every corridor looks the same. Somewhere in the darkness, heavy hooves scrape against stone and the Minotaur\'s breath comes in clouds of steam. There is no thread to guide you here — only your blade.',
			narrativeAfter: 'The Minotaur crashes to the ground, shaking the very walls. A path opens where none existed before. Daedalus\'s masterwork has a new master.',
			narrativeVictory: 'The maze crumbles around the fallen beast. You emerge into Cretan sunlight, victorious.',
			narrativeDefeat: 'The Minotaur\'s horns find their mark. You are just another lost soul in the endless maze.',
			aiHeroId: 'hero-hermes', aiHeroClass: 'rogue',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.easy,
			bossRules: [], prerequisiteIds: ['greek-1'],
			rewards: [{ type: 'rune', amount: 25 }],
			realm: 'labyrinth',
			campaignArmy: { king: 'king-gaia', queen: 'hero-sinmara', rook: 'hero-hephaestus', bishop: 'hero-demeter', knight: 'hero-hermes' },
		},
		{
			id: 'greek-3', chapterId: 'greek', missionNumber: 3,
			name: 'Medusa\'s Gaze',
			description: 'Face the Gorgon Queen in her temple of stone.',
			narrativeBefore: 'Stone statues line the temple floor — warriors frozen mid-scream, their faces locked in eternal terror. Medusa\'s hiss echoes from every direction, her serpent hair alive with venom. One glance from her eyes will end your journey forever. Do not look.',
			narrativeAfter: 'The Gorgon\'s head rolls across the temple floor, its power spent. The statues remain — a reminder that even the mightiest can fall to a single glance.',
			narrativeVictory: 'You avert your eyes at the final moment and strike true. Perseus would be proud.',
			narrativeDefeat: 'Your eyes meet hers for just an instant. Stone creeps up from your feet. Another statue for her gallery.',
			aiHeroId: 'hero-athena', aiHeroClass: 'mage',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.medusa,
			bossRules: [{ type: 'passive_damage', value: 1, description: 'Medusa\'s Petrifying Gaze deals 1 damage each turn' }],
			prerequisiteIds: ['greek-2'],
			rewards: [{ type: 'rune', amount: 30 }],
			realm: 'athens',
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-athena', rook: 'hero-baldur', bishop: 'hero-hera', knight: 'hero-nyx' },
		},
		{
			id: 'greek-4', chapterId: 'greek', missionNumber: 4,
			name: 'The Hydra of Lerna',
			description: 'Cut one head, two grow back. Defeat the immortal beast.',
			narrativeBefore: 'The swamp of Lerna bubbles with poison. The Hydra rises from the murk, nine heads weaving and snapping. Heracles himself struggled against this beast — and he was a demigod. You are not. Cut a head and two more sprout, hissing with renewed fury.',
			narrativeAfter: 'The final head falls, cauterized before it can regenerate. The swamp falls silent. Even immortality has its limits.',
			narrativeVictory: 'You seal each wound with fire before it can grow anew. The Hydra finally lies still.',
			narrativeDefeat: 'For every head you sever, two more strike. The poison overwhelms you.',
			aiHeroId: 'hero-artemis', aiHeroClass: 'hunter',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.hydra,
			bossRules: [{ type: 'start_with_minion', cardId: 1010, description: 'The Hydra starts with a regenerating head on the battlefield' }],
			prerequisiteIds: ['greek-3'],
			rewards: [{ type: 'rune', amount: 35 }, { type: 'eitr', amount: 50 }],
			realm: 'aegean',
			campaignArmy: { king: 'king-brimir', queen: 'hero-shu', rook: 'hero-hephaestus', bishop: 'hero-poseidon', knight: 'hero-artemis' },
		},
		{
			id: 'greek-5', chapterId: 'greek', missionNumber: 5,
			name: 'Ares, God of War',
			description: 'The bloodthirsty god of war demands single combat.',
			narrativeBefore: 'The fields of Sparta run red. Ares descends in a whirlwind of bronze and fury, his eyes burning with insatiable bloodlust. "Finally," he growls, drawing a sword that has ended ten thousand lives. "Someone worth killing." He does not fight with strategy or cunning — only relentless, savage aggression.',
			narrativeAfter: 'Ares staggers back, ichor leaking from a wound no mortal should have been able to inflict. "Impressive," he snarls, then vanishes in a flash of crimson light.',
			narrativeVictory: 'The God of War kneels. Even bloodlust has its match in iron will.',
			narrativeDefeat: 'Ares stands over you, laughing. War always wins in the end.',
			aiHeroId: 'hero-hephaestus', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.ares,
			bossRules: [{ type: 'extra_health', value: 5, description: 'Ares has 105 health' }],
			prerequisiteIds: ['greek-4'],
			rewards: [{ type: 'rune', amount: 40 }],
			realm: 'sparta',
			campaignArmy: { king: 'king-surtr', queen: 'hero-sinmara', rook: 'hero-ares', bishop: 'hero-hestia', knight: 'hero-apollo' },
		},
		{
			id: 'greek-6', chapterId: 'greek', missionNumber: 6,
			name: 'Poseidon\'s Wrath',
			description: 'The seas rage as the Earth-Shaker turns his trident upon you.',
			narrativeBefore: 'The Aegean heaves and splits. Poseidon rises from the deep, his trident crackling with the fury of every storm that has ever broken a ship. Tidal waves crash around you as sea creatures answer their master\'s call. The god of the sea does not forgive trespassers.',
			narrativeAfter: 'The waters calm. Poseidon submerges with a final, thunderous wave. The sea remembers your name now — and it will think twice before attacking again.',
			narrativeVictory: 'The tides recede. Even the ocean must bow to true courage.',
			narrativeDefeat: 'The sea swallows you whole. Poseidon adds another shipwreck to his collection.',
			aiHeroId: 'hero-poseidon', aiHeroClass: 'shaman',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.poseidon,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Poseidon has 110 health' },
				{ type: 'bonus_draw', value: 1, description: 'Poseidon draws an extra card from the depths' },
			],
			prerequisiteIds: ['greek-5'],
			rewards: [{ type: 'rune', amount: 50 }, { type: 'card', cardId: 1200 }],
			realm: 'aegean',
			campaignArmy: { king: 'king-brimir', queen: 'hero-zeus', rook: 'hero-hephaestus', bishop: 'hero-poseidon', knight: 'hero-hermes' },
		},
		{
			id: 'greek-7', chapterId: 'greek', missionNumber: 7,
			name: 'Hades\' Bargain',
			description: 'The lord of the dead offers a terrible deal. Refuse, and face his wrath.',
			narrativeBefore: 'Hades sits upon his obsidian throne, Persephone silent at his side. "I have a proposition," he says, his voice cold as the grave. "Serve me, and I will grant you power beyond mortal comprehension. Refuse..." His eyes flare with ghostly flame. "And I will add you to my collection."',
			narrativeAfter: '"So be it," Hades whispers as shadows retreat. "You have earned a rare thing — my respect. But remember: all souls come to me eventually."',
			narrativeVictory: 'Even the lord of the dead cannot hold dominion over an unbroken spirit.',
			narrativeDefeat: 'Hades smiles. "They all refuse at first." The shadows close in.',
			aiHeroId: 'hero-hades', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.hades,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Hades has 110 health' },
				{ type: 'passive_damage', value: 1, description: 'The Underworld drains 1 health each turn' },
			],
			prerequisiteIds: ['greek-6'],
			rewards: [{ type: 'rune', amount: 55 }],
			realm: 'underworld',
			campaignArmy: { king: 'king-tartarus', queen: 'hero-hades', rook: 'hero-vidar', bishop: 'hero-aphrodite', knight: 'hero-nyx' },
		},
		{
			id: 'greek-8', chapterId: 'greek', missionNumber: 8,
			name: 'Athena\'s Trial',
			description: 'The goddess of wisdom and war tests your strategic mind.',
			narrativeBefore: 'Athena stands in her temple, grey-eyed and terrible in her calm. She does not rage like Ares or storm like Poseidon. She simply watches, calculates, and strikes with perfect precision. "Brute force will not avail you here," she says, adjusting the aegis on her arm. "Show me your mind."',
			narrativeAfter: 'Athena lowers her spear and the slightest smile crosses her lips. "Wisdom and courage together. Rare indeed." She offers a single olive branch — the highest honor Athens can bestow.',
			narrativeVictory: 'The goddess of strategy herself concedes. Your mind proved equal to Olympian intellect.',
			narrativeDefeat: 'Athena predicted every move before you made it. Wisdom without equal.',
			aiHeroId: 'hero-hyperion', aiHeroClass: 'mage',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.athena,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Athena has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Athena starts with +1 mana from divine wisdom' },
			],
			prerequisiteIds: ['greek-7'],
			rewards: [{ type: 'rune', amount: 60 }, { type: 'eitr', amount: 100 }],
			realm: 'athens',
			campaignArmy: { king: 'king-gaia', queen: 'hero-athena', rook: 'hero-heimdall', bishop: 'hero-hera', knight: 'hero-hermes' },
		},
		{
			id: 'greek-9', chapterId: 'greek', missionNumber: 9,
			name: 'The Titan Kronos',
			description: 'Father of the gods rises from Tartarus to reclaim his throne.',
			narrativeBefore: 'The earth splits open. Kronos, father of Zeus, breaker of the first age, hauls himself from the pit of Tartarus. He is vast beyond comprehension, his scythe dripping with the blood of the age he devoured. "I ate my own children," he rumbles. "What chance do you think you have?"',
			narrativeAfter: 'Kronos sinks back into Tartarus, his grip on the world broken once more. But time is patient. He will wait in the dark, as he always has, for another chance to rise.',
			narrativeVictory: 'The Father of Time falls. Even eternity must yield to the present moment.',
			narrativeDefeat: 'Time devours all things. You are no exception.',
			aiHeroId: 'hero-chronos', aiHeroClass: 'mage',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.kronos,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Kronos has 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Kronos wields primordial power (+2 mana)' },
			],
			prerequisiteIds: ['greek-8'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 1250 }],
			realm: 'delphi',
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-chronos', rook: 'hero-logi', bishop: 'hero-demeter', knight: 'hero-apollo' },
		},
		{
			id: 'greek-10', chapterId: 'greek', missionNumber: 10,
			name: 'Zeus, King of Olympus',
			description: 'The thunderer himself descends to judge your worthiness.',
			narrativeBefore: 'Clouds part above Mount Olympus as Zeus descends in a pillar of lightning. His eyes crackle with the power of every storm that has ever raged across the Mediterranean. He is the King of the Gods, the wielder of the Master Bolt, and he has watched your journey across his realm with growing interest. "You have defeated my brothers. My children. Even a Titan. Now face the king."',
			narrativeAfter: 'Zeus hurls his final thunderbolt into the sky and laughs — not in anger, but in genuine delight. "At last! A mortal worth the trouble!" Lightning dances across Olympus as the gods themselves cheer. The Olympian chapter is complete.',
			narrativeVictory: 'The King of Gods inclines his head. You have earned the thunder\'s respect. Olympus will remember.',
			narrativeDefeat: 'Lightning unmakes you. Zeus returns to his throne, disappointed. "Perhaps the next mortal."',
			aiHeroId: 'hero-zeus', aiHeroClass: 'mage',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.zeus,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Zeus has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Zeus commands divine mana (+2)' },
				{ type: 'bonus_draw', value: 1, description: 'Zeus draws an extra card each turn' },
			],
			prerequisiteIds: ['greek-9'],
			rewards: [{ type: 'rune', amount: 100 }, { type: 'card', cardId: 1300 }, { type: 'pack', amount: 2 }],
			realm: 'olympus',
			campaignArmy: { king: 'king-tartarus', queen: 'hero-zeus', rook: 'hero-ares', bishop: 'hero-poseidon', knight: 'hero-apollo' },
		},
	],
};
