import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

export const norseChapter: CampaignChapter = {
	id: 'norse',
	name: 'Echoes of Ymir',
	faction: 'norse',
	description: 'Journey through the Nine Realms as the forces of Ragnarok gather. The giants remember Ymir\'s blood. Bergelmir survived. And vengeance stirs in every frozen corner of the world tree.',
	chapterReward: [{ type: 'pack', amount: 3 }, { type: 'rune', amount: 200 }],
	cinematicIntro: {
		title: 'The Primordial Blood',
		style: 'Diablo-style dark fantasy CGI — sweeping camera, slow-motion violence, heavy orchestral score with Norse throat-singing, war horns, and deep bass drums. 3:30 runtime. Gravelly, ancient narrator.',
		scenes: [
			{
				narration: 'In the beginning... there was only the Ginnungagap. The yawning void. From the north came the venomous ice of Niflheim. From the south, the ravenous fire of Muspelheim. Where they met... life awoke in agony.',
				visualCue: 'Infinite darkness. Crashing walls of ice and flame collide in slow motion. Poisonous mist boils. Camera pushes through the chaos.',
				musicCue: 'Low, ominous strings. Distant howling wind.',
				durationHint: 15,
			},
			{
				narration: 'First came Ymir — the frost giant, father of all jotnar. Evil and vast, he spawned his kind from sweat and filth. His hunger knew no end.',
				visualCue: 'Massive, grotesque Ymir rising, eyes glowing blue-white. Frost giants claw out of his armpits and legs, roaring. He drinks from the void.',
				musicCue: 'Deep bass drums, building dread.',
				durationHint: 12,
			},
			{
				narration: 'But the gods sent forth Audumbla — the great cow of creation. Her milk fed the giant... while her tongue carved order from the ice.',
				visualCue: 'Majestic black cow appears in golden light. She licks massive salt-ice blocks. Over three days: hair, head, then full figure of Buri emerges — tall, fair, bearded, eyes like storm clouds. He stands powerful, unafraid.',
				musicCue: 'Golden horns, a moment of hope.',
				durationHint: 14,
			},
			{
				narration: 'Buri, the first of the Aesir. Mighty progenitor. He sired Borr — bridge between old blood and new.',
				visualCue: 'Quick montage: Buri alone in the ice. Flash of divine light. Borr appears — rugged, determined. He takes giantess Bestla as wife. Their three sons born in firelight: young Odin (one eye already sharp), Vili, Ve. They watch the giants multiply with growing dread.',
				musicCue: 'Strings build tension.',
				durationHint: 12,
			},
			{
				narration: 'The giants grew bold. Their chaos swallowed the void. Ymir\'s horde threatened to drown all that could be. So the old gods chose war.',
				visualCue: 'Camera sweeps across frozen battlefield. Buri and Borr, armored in crude bone and ice, stand with their grown sons. Buri raises a massive spear. Borr grips a jagged axe.',
				musicCue: 'War drums swell. Norse throat-singing begins.',
				durationHint: 10,
			},
			{
				narration: 'Buri and Borr led the charge — grandfather and father — so their sons might inherit a world.',
				visualCue: 'Epic battle sequence — brutal slow-mo: Buri charges through frost giants, spear flashing, slaying dozens. Ymir roars, swings a club the size of a mountain. Buri leaps, stabs Ymir\'s thigh — blood sprays like a geyser. Ymir backhands him. Buri crashes, broken but defiant. Borr roars, protects his sons, hacks at Ymir\'s leg. Ymir impales him through the chest with a frost shard. Borr gasps, still swinging as he dies.',
				musicCue: 'Full orchestra, crescendo of brass and drums.',
				durationHint: 45,
			},
			{
				narration: 'Buri fell first — the elder\'s sacrifice. Borr followed, shielding his bloodline with his final breath.',
				visualCue: 'Camera lingers on their bodies amid the chaos — heroic, bloodied, eyes open to the void.',
				musicCue: 'Strings soften, grieving tone.',
				durationHint: 8,
			},
			{
				narration: 'Then the sons of Borr answered.',
				visualCue: 'Odin, Vili, and Ve leap as one. Odin drives Gungnir straight into Ymir\'s throat. The giant screams — the sound shakes the heavens.',
				musicCue: 'Rising fury, drums and brass.',
				durationHint: 6,
			},
			{
				narration: 'Ymir fell. And with him... everything.',
				visualCue: 'Slow-motion cataclysm: Ymir collapses. An ocean of blood explodes outward — red tsunami. Giants drown screaming, dragged under. Audumbla stands on a shrinking ice floe, lowing mournfully one last time as she tries to lick a final block of creation. The crimson wave engulfs her. Her eyes close. She sinks.',
				musicCue: 'Choir and deep bass, apocalyptic.',
				durationHint: 18,
			},
			{
				narration: 'Even the primordial cow — mother of beginnings — perished in the flood of endings.',
				visualCue: 'The blood recedes. Ymir\'s colossal corpse lies across the void.',
				musicCue: 'Solemn silence, then soft strings.',
				durationHint: 6,
			},
			{
				narration: 'From the enemy\'s body the brothers forged the Nine Realms. Flesh became earth. Blood became sea. Bones became mountains. Skull became sky. Brains became clouds. And from the spark of their fathers\' sacrifice... Midgard and Asgard rose.',
				visualCue: 'Montage of creation: Land rising, trees sprouting, sun and moon placed in the sky. Odin stands alone on a new mountain peak, wind whipping his cloak, two ravens circling. He looks back at the battlefield where Buri and Borr\'s bodies have become part of the new world — subtle silhouettes in the stone.',
				musicCue: 'Majestic horn theme, hopeful but bittersweet.',
				durationHint: 20,
			},
			{
				narration: 'Thus the gods were born in blood and loss. The first gods gave their lives... so that we might have ours. But the giants remember the slaughter. Bergelmir survived.',
				visualCue: 'Final shot: a lone frost giant drifting on a blood-soaked log, eyes burning with hatred, fading into darkness.',
				musicCue: 'Single low note, ominous. Fade to black.',
				durationHint: 12,
			},
		],
	},
	missions: [
		{
			id: 'norse-1', chapterId: 'norse', missionNumber: 1,
			name: 'The Awakening',
			description: 'A Draugr stirs in the frozen wastes of Niflheim.',
			narrativeBefore: 'The winds of Niflheim howl as ancient dead rise from their barrows. The draugr — restless corpses of Norse warriors denied Valhalla — claw their way from frozen graves. They are the lowest servants of Hel, mindless husks driven by jealousy of the living. Even the weakest foe in the Nine Realms demands respect.',
			narrativeAfter: 'The draugr crumbles to dust. But the stirring you feel in the earth tells you this is only the beginning. Something ancient is waking across the Nine Realms — an echo of Ymir\'s blood, calling his descendants to vengeance.',
			narrativeVictory: 'The undead warrior falls. Even death\'s foot soldiers cannot stop your advance into the Nine Realms.',
			narrativeDefeat: 'The draugr\'s frozen grip closes around your throat. Niflheim claims another soul for the mist.',
			aiHeroId: 'norse-warrior-1', aiHeroClass: 'warrior',
			aiDeckCardIds: [20001,20001,20002,20002,20003,20003,20004,20004,20005,20005,20010,20010,20011,20011,20012,20012,20013,20013,20014,20014,20015,20015,20020,20020,20021,20021,20022,20022,20023,20023],
			aiProfile: AI_PROFILES.easy, bossRules: [], prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 20 }],
			realm: 'niflheim',
		},
		{
			id: 'norse-2', chapterId: 'norse', missionNumber: 2,
			name: 'Wolves of Ironwood',
			description: 'Fenrir\'s lesser kin hunt in packs across the frozen forest.',
			narrativeBefore: 'Jarnvidr — the Ironwood — is where the giantess Angrboda raised her monstrous children. Fenrir\'s brood still roams here, wolves with iron-grey pelts and eyes that burn like forge-coals. They hunt in relentless packs, testing prey with feints before the alpha strikes. In the distance, a shadow far larger than any wolf watches from the treeline.',
			narrativeAfter: 'The pack scatters as their alpha falls. Deeper in the forest, that massive shadow shifts and a low growl shakes the snow from the pines. Fenrir himself is not yet free — but his children prepare the way.',
			narrativeVictory: 'The wolves of Ironwood scatter before you. But the Fenris-Wolf\'s shadow grows longer with each passing day.',
			narrativeDefeat: 'The pack drags you into the Ironwood. Angrboda\'s children feast tonight.',
			aiHeroId: 'norse-hunter-1', aiHeroClass: 'hunter',
			aiDeckCardIds: [20030,20030,20031,20031,20032,20032,20033,20033,20034,20034,20035,20035,20036,20036,20037,20037,20038,20038,20039,20039,20040,20040,20041,20041,20042,20042,20043,20043,20044,20044],
			aiProfile: AI_PROFILES.fenrir, bossRules: [], prerequisiteIds: ['norse-1'],
			rewards: [{ type: 'rune', amount: 25 }],
			realm: 'jotunheim',
		},
		{
			id: 'norse-3', chapterId: 'norse', missionNumber: 3,
			name: 'The Bridge of Bifrost',
			description: 'Heimdall\'s Einherjar guard the only road to Asgard.',
			narrativeBefore: 'The Rainbow Bridge blazes with all the colors of creation, connecting Midgard to Asgard across the void. Heimdall\'s Einherjar stand guard — warriors hand-picked by the all-seeing god to defend the only road to the realm of the gods. None pass without proving they carry the blood of worthy ancestors. The Gjallarhorn gleams at Heimdall\'s hip — when it sounds, Ragnarok has begun.',
			narrativeAfter: 'The guardians step aside. High above, Heimdall himself watches from Himinbjorg, his golden eyes measuring your soul across impossible distance. He has seen your past and your future. He says nothing — which is approval enough.',
			narrativeVictory: 'The guardians of Bifrost part before you. The road to Asgard opens.',
			narrativeDefeat: 'Bifrost rejects the unworthy. You tumble into the void between worlds.',
			aiHeroId: 'norse-paladin-1', aiHeroClass: 'paladin',
			aiDeckCardIds: [20050,20050,20051,20051,20052,20052,20053,20053,20054,20054,20055,20055,20056,20056,20057,20057,20058,20058,20059,20059,20060,20060,20061,20061,20062,20062,20063,20063,20064,20064],
			aiProfile: AI_PROFILES.medium, bossRules: [], prerequisiteIds: ['norse-2'],
			rewards: [{ type: 'rune', amount: 30 }],
			realm: 'asgard',
		},
		{
			id: 'norse-4', chapterId: 'norse', missionNumber: 4,
			name: 'Ratatosk\'s Riddles',
			description: 'The squirrel of Yggdrasil speaks in puzzles and traps.',
			narrativeBefore: 'Ratatosk scurries along the bark of Yggdrasil, the World Tree that connects all Nine Realms. This sharp-toothed squirrel spends eternity carrying insults between the eagle Vedrfolnir at the crown and the dragon Nidhogg gnawing the roots. He knows every secret whispered between branches. "Answer my riddles," he chitters, "or I\'ll tell Nidhogg where to find your thread of fate."',
			narrativeAfter: 'Ratatosk cackles and vanishes into the bark, already composing insults for both eagle and dragon about your victory. The path upward through Yggdrasil is now open — but the squirrel will gossip about your every move.',
			narrativeVictory: 'The gossip of the World Tree scurries away, defeated by wit sharper than his teeth.',
			narrativeDefeat: 'Ratatosk carries news of your failure to every branch of Yggdrasil. Even the roots laugh.',
			aiHeroId: 'norse-mage-1', aiHeroClass: 'mage',
			aiDeckCardIds: [20070,20070,20071,20071,20072,20072,20073,20073,20074,20074,20075,20075,20076,20076,20077,20077,20078,20078,20079,20079,20080,20080,20081,20081,20082,20082,20083,20083,20084,20084],
			aiProfile: AI_PROFILES.ratatosk,
			bossRules: [{ type: 'bonus_draw', value: 1, description: 'Ratatosk draws an extra card each turn' }],
			prerequisiteIds: ['norse-3'],
			rewards: [{ type: 'rune', amount: 35 }, { type: 'dust', amount: 50 }],
			realm: 'midgard',
		},
		{
			id: 'norse-5', chapterId: 'norse', missionNumber: 5,
			name: 'The Forge of the Dwarves',
			description: 'Brokkr and Sindri forge weapons against you.',
			narrativeBefore: 'Beneath Svartalfheim, the dwarven forges glow with the heat of a captive star. Brokkr and his brother Sindri — the master smiths who crafted Thor\'s hammer Mjolnir, Odin\'s ring Draupnir, and Freyr\'s golden boar Gullinbursti — stand before their anvil. Brokkr wagers his head that you cannot withstand a weapon forged specifically to destroy you. He begins hammering, and the metal screams.',
			narrativeAfter: 'Brokkr pounds his anvil in frustration. "Take your prize," he growls, sliding a gleaming blade across the forge. Sindri, ever the quieter brother, nods with grudging respect. "We forged Mjolnir. We can admit when something is harder than our steel."',
			narrativeVictory: 'The dwarven forge falls silent. Brokkr concedes — a rarer event than the forging of Mjolnir itself.',
			narrativeDefeat: 'Brokkr\'s latest creation finds its mark. Another masterwork for the halls of Svartalfheim.',
			aiHeroId: 'norse-warrior-2', aiHeroClass: 'warrior',
			aiDeckCardIds: [20090,20090,20091,20091,20092,20092,20093,20093,20094,20094,20095,20095,20096,20096,20097,20097,20098,20098,20099,20099,20100,20100,20101,20101,20102,20102,20103,20103,20104,20104],
			aiProfile: AI_PROFILES.brokkr,
			bossRules: [{ type: 'extra_mana', value: 1, description: 'Brokkr starts with +1 mana crystal' }],
			prerequisiteIds: ['norse-4'],
			rewards: [{ type: 'rune', amount: 40 }],
			realm: 'svartalfheim',
		},
		{
			id: 'norse-6', chapterId: 'norse', missionNumber: 6,
			name: 'Hel\'s Domain',
			description: 'The goddess of the dead commands an army of shades.',
			narrativeBefore: 'Helheim stretches before you — a realm of ice and shadow where those who died of sickness or old age spend eternity. Hel, daughter of Loki and the giantess Angrboda, sits on her throne Eljudnir. Half her face is beautiful as any goddess; the other half is rotting corpse. Her dish is called Hunger, her knife is Famine, and her bed is Sickness. She does not fight with brute force — she drains life itself, turning your own mortality against you.',
			narrativeAfter: 'Hel retreats deeper into her hall of the dead. "You have earned your life today," she whispers. "But Ragnarok comes for all. When it does, I will march my army of the dishonored dead against Asgard itself. And you will be among them — eventually."',
			narrativeVictory: 'The queen of the dishonored dead cannot claim you. Life burns too bright in your veins.',
			narrativeDefeat: 'Hel adds you to her collection. Not Valhalla, not Folkvangr — just the cold silence of her hall.',
			aiHeroId: 'norse-warlock-1', aiHeroClass: 'warlock',
			aiDeckCardIds: [20110,20110,20111,20111,20112,20112,20113,20113,20114,20114,20115,20115,20116,20116,20117,20117,20118,20118,20119,20119,20120,20120,20121,20121,20122,20122,20123,20123,20124,20124],
			aiProfile: AI_PROFILES.hel,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Hel has 110 health' },
				{ type: 'passive_damage', value: 1, description: 'Hel deals 1 damage to your hero each turn' },
			],
			prerequisiteIds: ['norse-5'],
			rewards: [{ type: 'rune', amount: 50 }, { type: 'card', cardId: 20200 }],
			realm: 'helheim',
		},
		{
			id: 'norse-7', chapterId: 'norse', missionNumber: 7,
			name: 'Jormungandr Stirs',
			description: 'The World Serpent rises from the deep.',
			narrativeBefore: 'The seas of Midgard churn as Jormungandr, the Midgard Serpent, lifts its massive head from the ocean floor. Cast into the sea by Odin as an infant, this child of Loki grew until it encircled the entire world, biting its own tail. Its venom poisons the very air — when it releases its tail at Ragnarok, the world ends. Thor is fated to slay it and die from the poison. Today, you face what even the God of Thunder fears.',
			narrativeAfter: 'The Serpent sinks beneath the waves, wounded but alive. It will not release its tail today — but the tremors of your battle have been felt in every realm. Even Odin felt the ripple from Hlidskjalf.',
			narrativeVictory: 'The World Serpent retreats beneath the waves. You have delayed the first sign of Ragnarok.',
			narrativeDefeat: 'Jormungandr\'s venom clouds your vision. The sea swallows you as it will one day swallow the world.',
			aiHeroId: 'norse-shaman-1', aiHeroClass: 'shaman',
			aiDeckCardIds: [20130,20130,20131,20131,20132,20132,20133,20133,20134,20134,20135,20135,20136,20136,20137,20137,20138,20138,20139,20139,20140,20140,20141,20141,20142,20142,20143,20143,20144,20144],
			aiProfile: AI_PROFILES.jormungandr,
			bossRules: [{ type: 'extra_health', value: 15, description: 'Jormungandr has 115 health' }],
			prerequisiteIds: ['norse-6'],
			rewards: [{ type: 'rune', amount: 55 }],
			realm: 'midgard',
		},
		{
			id: 'norse-8', chapterId: 'norse', missionNumber: 8,
			name: 'Loki\'s Gambit',
			description: 'The Trickster god plays games within games.',
			narrativeBefore: 'Loki Laufeyjarson — blood-brother to Odin, father of monsters, architect of Baldur\'s death. He grins from his throne of lies, shape-shifting between man, woman, salmon, and fly as casually as you change thoughts. Nothing he says is true and nothing he says is false. He cut Sif\'s golden hair for sport. He guided the mistletoe that killed Baldur. He will captain Naglfar, the ship of dead men\'s nails, at Ragnarok. "Let us play a game," he says, shuffling cards that shift and change in his hands. "The rules are whatever I say they are."',
			narrativeAfter: '"Clever, clever mortal," Loki laughs, vanishing in a shimmer of green flame. "But the last trick is always mine. Ask Baldur — oh wait, you can\'t." Even in defeat, the Trickster wins something. You can feel it.',
			narrativeVictory: 'You out-trick the Trickster. Loki\'s smile falters — a sight rarer than Ragnarok itself.',
			narrativeDefeat: 'Loki\'s gambit succeeds. You never even saw the real game being played.',
			aiHeroId: 'norse-rogue-1', aiHeroClass: 'rogue',
			aiDeckCardIds: [20150,20150,20151,20151,20152,20152,20153,20153,20154,20154,20155,20155,20156,20156,20157,20157,20158,20158,20159,20159,20160,20160,20161,20161,20162,20162,20163,20163,20164,20164],
			aiProfile: AI_PROFILES.loki,
			bossRules: [{ type: 'bonus_draw', value: 2, description: 'Loki draws 2 extra cards each turn' }],
			prerequisiteIds: ['norse-7'],
			rewards: [{ type: 'rune', amount: 60 }, { type: 'dust', amount: 100 }],
			realm: 'jotunheim',
		},
		{
			id: 'norse-9', chapterId: 'norse', missionNumber: 9,
			name: 'Thor\'s Challenge',
			description: 'The God of Thunder demands single combat.',
			narrativeBefore: 'Thunder splits the sky above Asgard as Thor Odinson descends in a column of lightning. Son of Odin and the earth-giantess Jord, he is the protector of both gods and mortals — the strongest of all the Aesir. Mjolnir crackles in his iron-gloved grip, the belt Megingjord doubling his already godlike strength. He is loud, honest, and unstoppable. "I have heard of your deeds across the Nine Realms," he bellows. "Prove you are worthy to stand against Ragnarok — not with tricks, but with strength."',
			narrativeAfter: 'Thor lowers Mjolnir and claps you on the shoulder hard enough to crack stone. "You fight well, mortal. When Ragnarok comes, I would have you at my side — between me and the Serpent." Coming from the God of Thunder, there is no higher honor.',
			narrativeVictory: 'The God of Thunder kneels in respect. Mjolnir itself hums with recognition of your worth.',
			narrativeDefeat: 'A single blow of Mjolnir. That is all it takes. Thor collects no trophies — your survival would have been trophy enough.',
			aiHeroId: 'norse-warrior-3', aiHeroClass: 'warrior',
			aiDeckCardIds: [20170,20170,20171,20171,20172,20172,20173,20173,20174,20174,20175,20175,20176,20176,20177,20177,20178,20178,20179,20179,20180,20180,20181,20181,20182,20182,20183,20183,20184,20184],
			aiProfile: AI_PROFILES.thor,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Thor has 110 health' },
				{ type: 'extra_mana', value: 2, description: 'Thor starts with +2 mana crystals' },
			],
			prerequisiteIds: ['norse-8'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 20250 }],
			realm: 'asgard',
		},
		{
			id: 'norse-10', chapterId: 'norse', missionNumber: 10,
			name: 'Odin, the Allfather',
			description: 'The king of the gods tests you one final time.',
			narrativeBefore: 'Odin Borsson sits upon Hlidskjalf, the high seat from which he sees all things across all Nine Realms. He sacrificed his eye at Mimir\'s Well for wisdom. He hung himself from Yggdrasil for nine days and nights, pierced by his own spear, to learn the runes. His ravens Huginn and Muninn — Thought and Memory — circle overhead, whispering everything they have seen. He is the god of war, death, poetry, and knowledge. He does not fight with brute strength like Thor, nor with tricks like Loki. He fights with the certainty of someone who already knows how the story ends. "I have watched your journey," he says, his single eye piercing your soul. "I know your fate. Show me you can change it."',
			narrativeAfter: 'Odin rises from Hlidskjalf. For the first time in eons, the Allfather looks surprised. "You were not in my visions," he says quietly. "That has not happened since I gave my eye." Huginn and Muninn land on his shoulders, chattering. "Perhaps Ragnarok is not as certain as I believed. You have earned the respect of Asgard — and something rarer: the curiosity of the Allfather." The chapter of the Norse is complete.',
			narrativeVictory: 'The Allfather himself is taken aback. You exist outside fate — and that changes everything.',
			narrativeDefeat: 'Odin saw this outcome before the battle began. He returns to Hlidskjalf, weary but unsurprised.',
			aiHeroId: 'norse-priest-1', aiHeroClass: 'priest',
			aiDeckCardIds: [20190,20190,20191,20191,20192,20192,20193,20193,20194,20194,20195,20195,20196,20196,20197,20197,20198,20198,20199,20199,20200,20200,20201,20201,20202,20202,20203,20203,20204,20204],
			aiProfile: AI_PROFILES.odin,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Odin has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Odin starts with +2 mana crystals' },
				{ type: 'bonus_draw', value: 1, description: 'Odin draws an extra card each turn' },
			],
			prerequisiteIds: ['norse-9'],
			rewards: [{ type: 'rune', amount: 100 }, { type: 'card', cardId: 20300 }, { type: 'pack', amount: 2 }],
			realm: 'asgard',
		},
	],
};
