/**
 * Neutral spells and tech cards for Hearthstone clone
 * This collection includes utility spells and tech cards that can be used in any deck
 */
import { CardData } from '../types';

/**
 * Collection of neutral spells and tech cards from Hearthstone
 * These cards provide utility effects and tech choices against specific strategies
 */
export const   neutralSpellsAndTech: CardData[] = [
  {
      id: 31003,

      name: "Potion of the Gods",
      manaCost: 1,

      type: "spell",
      rarity: "epic",

      description: "Create a custom spell.",
      heroClass: "neutral",
      class: "Neutral",
      collectible: false, // Generated by Kazakus
      spellEffect: {
        type: "custom",


        requiresTarget: false

      
       }
    },
  {
  id: 31004,
  
  name: "Silence",
  manaCost: 0,
  
  type: "spell",
  rarity: "common",
  
  description: "Silence a minion.",
  heroClass: "neutral",
      class: "Neutral",
  
    spellEffect: {
  type: "silence",
  
  requiresTarget: true,
  targetType: "any_minion"
  
  
  
  },
      collectible: true
  },
  {
      id: 31005,

      name: "Master of Runes",
      manaCost: 6,

      attack: 5,
      health: 5,

      type: "minion",
      rarity: "legendary",

      description: "Battlecry: Set each player to 5 Mana Crystals.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      battlecry: {
        type: "mind_control_random",
        condition: "opponent_minions_4",
        requiresTarget: false
      },
      collectible: true
  },
  {
      id: 31007,

      name: "Mighty Hunter of the Realms",
      manaCost: 5,

      attack: 4,
      health: 2,

      type: "minion",
      rarity: "epic",

      description: "Battlecry: Destroy a minion with 7 or more Attack.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      battlecry: {
        type: "mind_control_random",
        condition: "opponent_minions_4",
        requiresTarget: false
      },
      collectible: true
  },
  {
      id: 31008,

      name: "Shadow Spirit of the Void",
      manaCost: 6,

      attack: 4,
      health: 6,

      type: "minion",
      rarity: "epic",

      description: "Battlecry: Destroy all 1-Cost spells in both hands and decks.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      battlecry: {
        type: "mind_control_random",
        condition: "opponent_minions_4",
        requiresTarget: false
      },
      collectible: true
  },
  {
      id: 31009,

      name: "Breaker of Seals",
      manaCost: 4,

      attack: 2,
      health: 4,

      type: "minion",
      rarity: "rare",

      description: "Battlecry: Destroy all enemy Secrets. Gain +1/+1 for each Secret destroyed.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      battlecry: {
        type: "mind_control_random",
        condition: "opponent_minions_4",
        requiresTarget: false
      },
      collectible: true
  },
  {
      id: 31010,

      name: "Ravenous Crab of the Depths",
      manaCost: 1,

      attack: 1,
      health: 2,

      type: "minion",
      rarity: "epic",

      description: "Battlecry: Destroy a Murloc and gain +2/+2.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      race: "beast",
      battlecry: {
        type: "destroy_tribe",
        tribe: "murloc",
        buffs: {
          attack: 2,
          health: 2
        },
        requiresTarget: true,
        targetType: "murloc"
      },
      collectible: true
  },
  {
      id: 31011,

      name: "Primal Crawler of the Wild",
      manaCost: 2,

      attack: 2,
      health: 3,

      type: "minion",
      rarity: "rare",

      description: "Battlecry: Destroy a Pirate and gain +1/+1.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      race: "beast",
      battlecry: {
        type: "destroy_tribe",
        tribe: "pirate",
        buffs: {
          attack: 1,
          health: 1
        },
        requiresTarget: true,
        targetType: "pirate"
      },
      collectible: true
  },
  {
  id: 31014,
  
  name: "Fallen Priest of the Abyss",
  manaCost: 4,
  
  attack: 4,
  health: 2,
  
  type: "minion",
  rarity: "common",
  
  description: "Whenever one of your other minions dies, draw a card.",
  heroClass: "neutral", // Special handling in game logic for death trigger
  
  class: "Neutral",
      collectible: true
  },
  {
      id: 31015,

      name: "Mind Thief of the Gods",
      manaCost: 3,

      attack: 3,
      health: 3,

      type: "minion",
      rarity: "rare",

      description: "Battlecry: If your opponent has 4 or more minions, take control of one at random.",
      keywords: ["battlecry"],

      heroClass: "neutral",
      class: "Neutral",
      battlecry: {
        type: "mind_control_random",
        condition: "opponent_minions_4",
        requiresTarget: false
      },
      collectible: true
  }
];

// Export neutral spells and tech cards
export default neutralSpellsAndTech;